### snokadb.se
* [#13](https://github.com/salgo60/ifkdb/issues/13)
* Notebook [13_snokadb_se](https://github.com/salgo60/ifkdb/blob/main/Notebook/13_snokadb_se.ipynb)

In [1]:
from datetime import datetime
start_time  = datetime.now()
print("Last run: ", start_time)

Last run:  2026-03-29 07:22:57.532885

In [2]:
import nest_asyncio
nest_asyncio.apply()

In [3]:
import asyncio
import re
import pandas as pd
from playwright.async_api import async_playwright

async def scrape_players():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        await page.goto(
            "https://snokadb.se/spelare",
            wait_until="domcontentloaded",
            timeout=60000
        )

        # ge React lite tid
        await page.wait_for_timeout(2000)

        await page.wait_for_selector("table")

        rows = await page.query_selector_all("table tbody tr")
        data = []

        for row in rows:
            cols = await row.query_selector_all("td")
            if len(cols) < 4:
                continue

            raw_name = await cols[0].inner_text()
            name = raw_name.strip()

            seasons = (await cols[1].inner_text()).strip()
            matches = (await cols[2].inner_text()).strip()
            goals = (await cols[3].inner_text()).strip()

            link = await row.query_selector("a")
            href = await link.get_attribute("href") if link else ""
            slug = href.split("/")[-1] if href else ""

            data.append({
                "snokadb_id": slug,
                "name": name,
                "seasons": seasons,
                "matches": matches,
                "goals": goals
            })

        await browser.close()

    return pd.DataFrame(data)

df = asyncio.run(scrape_players())
df.head(), len(df)

(           snokadb_id                  name                 seasons matches  \
 0      abdoulie-tamba      🇬🇦Abdoulie Tamba                    2025       5
 1  alexander-fransson  🇸🇪Alexander Fransson     2013 och 7 säsonger     201
 2      anton-eriksson      🇸🇪Anton Eriksson  2022, 2023, 2024, 2025      79
 3        axel-bronner        🇸🇪Axel Brönner                    2025      16
 4   christoffer-nyman   🇸🇪Christoffer Nyman    2010 och 13 säsonger     329

   goals
 0     0
 1    17
 2     0
 3     0
 4   112  ,
 584)

In [4]:
import asyncio
import re
from playwright.async_api import async_playwright


async def fetch_birthdate(context, slug, semaphore):
    url = f"https://snokadb.se/spelare/{slug}"

    async with semaphore:
        page = await context.new_page()
        try:
            await page.goto("https://snokadb.se/spelare", wait_until="domcontentloaded", timeout=60000)
            # vänta lite extra (React)
            await page.wait_for_timeout(1000)

            content = await page.inner_text("body")

            match = re.search(r"Födelsedatum:\s*\"?(\d{4}-\d{2}-\d{2})\"?", content)

            birthdate = match.group(1) if match else ""
            print(slug, birthdate)

            return birthdate

        except Exception as e:
            print(f"Misslyckades för {slug}: {e}")
            return ""

        finally:
            await page.close()

        # liten paus mellan requests
        await asyncio.sleep(0.3)


async def enrich_parallel(df, max_concurrency=2):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context()
        semaphore = asyncio.Semaphore(max_concurrency)

        tasks = [
            fetch_birthdate(context, slug, semaphore)
            for slug in df["snokadb_id"]
        ]

        results = await asyncio.gather(*tasks)
        await browser.close()

    df = df.copy()
    df["birthdate"] = results
    return df

In [5]:
df = await enrich_parallel(df)

alexander-fransson
abdoulie-tamba
anton-eriksson
axel-bronner
christoffer-nyman
david-mitov-nilsson
filip-dagerstal
isak-andri-sigurgeirsson
moutaz-neffati
noel-sernelius
stephan-bolma
theo-krantz
tim-prica
ture-sandberg
ake-andersson
abbas-hassan
abderahman-kabous
abdulrazaq-ishaq
adin-bukva
alexander-jakobsen
alexander-petras
alexander-radesjo
alexander-ostlund
alfons-sampsted
algot-wulff
alhaji-kamara
allan-hasselmark
allan-johansson
allan-pettersson
amadeus-sogaard
anders-wikstrom
anders-whass
andreas-alm
andreas-blomqvist
andreas-dahlen
andreas-hadenius
andreas-haglund
andreas-johansson
andreas-lindberg
andreas-thomas
andreas-vaikla
andri-lucas-gudjohnsen
antti-sumiala
ari-freyr-skulason
armando-ibrakovic
armin-tankovic
arne-andersson
arne-eriksson
arne-rehnberg
arne-tornqvist
arnor-traustason
arnor-sigurdsson
arthur-astrand
astrit-ajdarevic
axel-jansson
axel-pressfeldt
axel-ramstedt
aziz-tafer
balazs-raboczki
bengt-carlson
bengt-carlsson
bengt-flisberg
bengt-gustavsson
bengt-lindstrom
bengt-nilsson
bengt-nyholm
bengt-rosen
bennard-yao-kumordzi
benny-wendt
bert-ottar-blom
bert-olof-haglund
bertil-andersson
bertil-remnegard
bill-bjorklund
birger-lonn
birger-rosengren
birkir-kristinsson
bjorn-franzen
bjorn-nordqvist
bo-la-fleur
bo-lagerlund
bo-larsson
bo-nilsson
bo-nilsson-nilmert
bo-ramsten
bo-stenqvist
bobbie-friberg-da-cruz
brian-mcdermott
bror-norrman
bruno-carlberg
bruno-santos
brynolf-ekelin
caio-mendes
carl-bjork
carl-erik-lindestrom
carl-evert-westerlund
christer-eriksson
christer-hult
christer-olsson
christer-sjolund
christopher-josue-meneses-barrantes
christopher-telo
curt-bernsten
curt-lovgren
curt-spogardh
dago-funes
dan-larsson
dan-svensson
dani-hamzo
daniel-bamberg
daniel-fredriksson
daniel-fritz-eid
daniel-sjolund
darko-mavrak
darrell-kamdem-tibell
david-adolfsson
david-andersson
david-boo-wiklander
david-moberg-karlsson
david-nordbeck
dawid-banaczek
dick-last
didace-burubwa
dime-jankulovski
dino-salihovic
diogo-oliveira
djordje-mrdjanin
donny-sundell
eddie-gustafsson
edvard-skagestad
edvin-johansson
edvin-tellgren
egzon-binaku
einar-karlsson
einar-steen
einar-wallsing
eine-fredriksson
eirik-dybendal
elof-pettersson
elis-hallberg
elon-lilden
elon-milden
eman-markovic
emanuel-chabo
emil-roback
emir-kujovi
eric-smith
erik-holmqvist
erik-jansson
erik-hoog
erik-karlsson
erik-norrby
evert-lager
felix-magro
filip-apelstav
fredrik-bild
fredrik-enerby
fritiof-hellichius
gardar-gunnlaugsson
gentrit-citaku
georg-ericson
georg-hogvall
george-parris
georgios-karathanasis
gerhard-torstensson
gert-hellberg
godswill-ekpolo
grant-igesund
gudmundur-mete
gudmundur-thorarinsson
gunnar-blomqvist
gunnar-goransson
gunnar-heidar-thorvaldsson
gunnar-karlsson
gunnar-moller
gunnar-nordahl
gunnar-persson
gunnar-ragnar
gunnar-stahl
gunnar-thor-gunnarsson
gustav-abrahamsson
goran-bergort
goran-e-karlsson
goran-gustafsson
goran-holm
goran-holter
goran-landberg
goran-linder
gosta-banan-andersson
gosta-andersson
gosta-berglund
gosta-lofgren
gosta-malm
gosta-nordahl
gosta-persson
gosta-ragnar
gote-arnell
gote-ortegren
halvar-carlbom
hamilton-thorp
hans-eriksson
hans-eskilsson
hans-holmertz
hans-karlsson
hans-larsson
hans-ottosson
hans-rosander
hans-amansson
harald-brask
harald-nyman
haris-laitinen
harry-bild
harry-fyhrberg
harry-risberg
harry-stanley
harry-westerlund
hasan-cetinkaya
henric-karlsson
henrik-castegren
henrik-skarnell
henrik-svedberg
henry-kallgren
herbert-sandin
holger-nyman
hakan-forsberg
hakan-larsson
hakan-lindman
hakan-lundstrom
hakan-malmqvist
hakan-pettersson
hakan-spjuth
ian-smith
igor-ponomarjev
imad-khalili
inge-danielsson
ingemar-johansson
ingemar-knutsson
isaac-kiese-thelin
isak-bergmann-johannesson
isak-pettersson
ismet-lushaku
isak-ssewankambo
issah-mohammed
ivo-vazgec
jacob-ortmark
james-frempong
jan-fimpen-eriksson
jan-connman
jan-eriksson
jan-heden
jan-jansson
jan-hellstrom
jan-johnsson
jan-kalen
jan-olsson
jan-svensson
jan-ake-jonsson
jani-sarajarvi
janne-hietanen
jean-carlos-de-brito
jesper-ceesay
jens-nilsson
jesper-lindvall
jesper-tolinsson
jevgenij-charlitov
jevgenij-kuznetsov
joachim-acheampong
joe-spiteri
joel-enarsson
johan-roxstrom
johannes-kristinn-bjarnason
johan-soderberg
johannes-vall
john-ohlin
johnny-einarsson
jon-gudni-fjoluson
jonas-andersson
jonas-bjurstrom
jonas-lind
jonas-persson
jonatan-gudni-arnarsson
jonas-wallerstedt
jonathan-levi
jonnie-efraimsson
jonny-rodlund
joonas-tamm
jordan-larsson
joseph-ceesay
junus-lindberg
karl-holmberg
karl-johansson
karl-kronkvist
karl-edvin-steen
karl-gustav-widegren
kasper-larsen
keith-pettersson
kenneth-aslund
kennet-andersson
kent-hellstrom
kent-lundqvist
kevin-amuneke
kevin-alvarez
kevin-hoog-jansson
kim-suominen
kjell-larsson
kleber-saarenpaa
knut-lindau
knut-nordahl
kojo-peprah-oppong
krister-norblad
kristoffer-arvhage
kristian-bergstrom
kurt-lovgren
kristoffer-khazeni
lambert-ramsten
laorent-shabani
lars-appelqvist
lars-berglund
lars-bergstrom
lars-eriksson
lars-krogh-gerson
lars-lindqvist
lars-svensson
lars-erik-bergstrand
lars-erik-wickberg
lars-erik-winge
lars-ake-berglund
leandre-griffit
leif-andersson
leif-anglesjo
leif-holmqvist
lennart-andersson
lennart-backman
lennart-carlsson
lennart-eriksson
lennart-fyhrberg
lennart-holmqvist
lennart-weidenstolpe
lennart-westren
lennart-wigren
leo-jonsson
linus-hallenius
linus-hellman
linus-wahlqvist
lucas-lima
magnus-gustafsson
magnus-jonsson
magnus-karlsson
maic-sema
magnus-samuelsson
malcolm-mcpherson
malte-palm
manasse-kusu
marcin-burkhardt
marcus-baggesen
marco-lund
marcus-falk-olander
marcus-johansson
marcus-sahlman
markus-hansson
markus-tornvall
martin-gustafsson
martin-smedberg-dalence
martin-gustavsson
martin-aslund
mathias-floren
mathias-gravem
mats-almgren
mats-johansson
mats-olofsson
mattias-flodstrom
mattias-ostberg
max-watson
michael-langer
mika-niskala
mikael-blomberg
mikael-eriksson
mikael-cupan
mikael-fyhrberg
mikael-granskog
mikael-hansson
mikael-kalpakidis
mikael-roth
mikael-lindskog
mikael-strom
mikael-torin
mirza-halvadzic
modou-barrow
morten-skjonsberg
neathan-gibson
nick-bosevski
nicklas-barkroth
niclas-eliasson
niclas-fredriksson
niclas-kindvall
niklas-gunnarsson
niklas-karlstrom
niklas-westberg
nikola-jokisic
nikola-tkalcic
nils-andersson
nils-eriksson
nils-gustafsson
nils-lennstrom
nils-liedholm
nils-ljungqvist
nils-persson
nils-olofsson
nils-sandin
nils-erik-tomell
nuredin-bakiu
okand-spelare
olie-hakansson
oliver-lonn
olle-bergstrom
olle-carlberg
olle-delborn
olle-eckerud
olle-hakansson
olle-nordin
olle-ringdahl
olle-siljeholm
olof-carlberg
olle-stahl
olof-olsson
oscar-bjorkqvist
oscar-holmqvist
oscar-jansson
ove-karlsson
ove-kindvall
ove-lindholm
ove-nordqvist
ove-stahlback
ove-tharning
patrik-andersson
patric-karlsson
patrik-jonsson
patrik-kieback
patrik-sandstrom
patrik-svensson
pelle-andersson
per-blohm
per-forsberg
per-hogmo
per-nilsson
per-lager
per-inge-jansson
per-olof-eek
peter-fyhr
peter-hagstrom
peter-hansen
peter-liljedahl
peter-lonn
peter-skoog
petrit-burrniku
petru-racu
pierre-gallo
pontus-almqvist
par-olof-olsson
ragnar-andersson
ragnar-eriksson
ranko-djordjic
rasmus-lauritsen
rawez-lawan
renato-braga
richard-spong
rickard-carlsson
riki-cakic
robert-hillstedt
robert-steiner
rodrigo-pontes
roger-lonn
roland-andersson
roland-niva
roland-pressfeldt
roland-svensson
rolf-rosenqvist
roy-bergstrom
runar-spannare
rune-lind
rune-pettersson
russell-mwafulirwa
samuel-adegbenro
sasa-sjanic
sead-haksabanovic
sebastian-andersson
sebastian-francisco
sebastian-jorgensen
shpetim-hasani
sigge-andersson
sigge-wigren
siim-luts
simon-dogan
simon-omekanda
simon-skrabb
simon-thern
siyabonga-siphika
slobodan-marovic
stefan-alven
stefan-broberg
stefan-pettersson
stefan-thordarson
sten-westerlund
stefan-tiborsson
stig-vammar-gustafsson
stig-vadstena-gustafsson
stig-bornhager
stig-falk
stig-kullman
stig-kordel
stig-palmgren
stig-sundqvist
sture-nilsson
sulo-vaattovaara
svante-larsson
sven-axbom
sven-b-dahlstrom
sven-bergstrom
sven-dahlstrom
sven-persson
sven-pettersson
sven-ringborg
sven-stromback
sven-widin
sven-ahman
sven-erik-svensson
sven-evert-hesselgren
sven-olof-bergman
sven-ake-wickberg
solve-flisberg
soren-andersen
soren-andersson
soren-nilsson
tage-ekstrom
tesfaldet-tekie
theodore-rask
thomas-andersson
thomas-cratz
thomas-johansson
thomas-magnusson
thomas-olof-andersson
thomas-olsson
thor-andre-olsen
thordur-thordarson
timmy-wilhelmsson
timmy-zetterqvist
tobias-rickhammar
tom-skarin
tomas-erixon
tomas-brolin
tomas-fransson
tomas-gustavsson
tomas-malm
tomas-mansson
tony-martinsson
tor-arne-fredheim
torbjorn-jonsson
tore-ekstrom
tore-gustavsson
tore-hjertqvist
torsten-elvhage
torsten-gronqvist
torsten-johansson
torsten-lindberg
ulf-hultberg
ulf-jansson
ulf-ottosson
valter-landstrom
victor-blomqvist
victor-lind
viktor-adsell-sjoberg
viktor-agardius
viktor-ronneklev
vito-hammershoj-mistrati
william-bergman
wyn-belotte
yahav-gurfinkel
yahya-kalley
ake-brynje
yngve-carlsson
ake-johansson
ake-larsson
ake-skarin
orjan-martinsson

In [6]:
df.to_csv("snokadb_players_raw.csv", index=False)

In [7]:
df

,snokadb_id,name,seasons,matches,goals,birthdate
0,abdoulie-tamba,🇬🇦Abdoulie Tamba,2025,5,0,
1,alexander-fransson,🇸🇪Alexander Fransson,2013 och 7 säsonger,201,17,
2,anton-eriksson,🇸🇪Anton Eriksson,"2022, 2023, 2024, 2025",79,0,
3,axel-bronner,🇸🇪Axel Brönner,2025,16,0,
4,christoffer-nyman,🇸🇪Christoffer Nyman,2010 och 13 säsonger,329,112,
...,...,...,...,...,...,...
579,ake-brynje,🇸🇪Åke Brynje,1939/40,1,0,
580,ake-johansson,🇸🇪Åke Johansson,1949/50 och 15 säsonger,321,1,
581,ake-larsson,🇸🇪Åke Larsson,"1939/40, 1940/41",8,0,
582,ake-skarin,🇸🇪Åke Skarin,1939/40,2,0,
583,orjan-martinsson,🇸🇪Örjan Martinsson,1959 och 8 säsonger,173,52,

In [10]:
import requests 
# Wikipedia/WIkidata  
import pandas as pd 
session = requests.Session()
session.headers.update({
    "User-Agent": "SnokaDB Wikidata research script (salgo60@msn.com)",
    "Accept": "application/sparql-results+json"
})
    
SPARQL = """
SELECT ?item ?itemLabel ?birthdate ?svwiki WHERE {
  ?item wdt:P54 wd:Q329607
  OPTIONAL { ?item wdt:P569 ?birthdate }
  OPTIONAL {
    ?svwiki schema:about ?item ;
            schema:isPartOf <https://sv.wikipedia.org/> .
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "sv,en". }
}
"""

url = "https://query.wikidata.org/sparql"
response = session.get(url, params={"query": SPARQL}, timeout=30)
response.raise_for_status()
data = response.json()

rows = []
for r in data["results"]["bindings"]: 
    rows.append({
        "wikidata_qid": r["item"]["value"].split("/")[-1],
        "name_wd": r["itemLabel"]["value"],
        "birthdate_wd": r.get("birthdate", {}).get("value", ""),
        "wikipedia_sv": r.get("svwiki", {}).get("value", "")
    })

wd_df = pd.DataFrame(rows)
wd_df.head(), len(wd_df)

(  wikidata_qid             name_wd          birthdate_wd wikipedia_sv
 0      Q308080  Abderrahman Kabous  1983-04-24T00:00:00Z
 1      Q576245    Kyle Lightbourne  1968-09-29T00:00:00Z
 2      Q629453    Slobodan Marović  1964-07-13T00:00:00Z
 3      Q634973      Janne Hietanen  1978-06-02T00:00:00Z
 4      Q724829     Balázs Rabóczki  1978-01-09T00:00:00Z             ,
 190)

In [11]:
# Matcha mot snokadb  
merged = df.merge(
    wd_df,
    left_on="name",
    right_on="name_wd",
    how="left"
)

merged[["snokadb_id","name","wikidata_qid","wikipedia_sv"]].head()

           snokadb_id                  name wikidata_qid wikipedia_sv
0      abdoulie-tamba      🇬🇦Abdoulie Tamba          NaN          NaN
1  alexander-fransson  🇸🇪Alexander Fransson          NaN          NaN
2      anton-eriksson      🇸🇪Anton Eriksson          NaN          NaN
3        axel-bronner        🇸🇪Axel Brönner          NaN          NaN
4   christoffer-nyman   🇸🇪Christoffer Nyman          NaN          NaN

In [12]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   snokadb_id    584 non-null    object
 1   name          584 non-null    object
 2   seasons       584 non-null    object
 3   matches       584 non-null    object
 4   goals         584 non-null    object
 5   birthdate     584 non-null    object
 6   wikidata_qid  0 non-null      object
 7   name_wd       0 non-null      object
 8   birthdate_wd  0 non-null      object
 9   wikipedia_sv  0 non-null      object
dtypes: object(10)
memory usage: 45.8+ KB

In [13]:
merged.head(20)

,snokadb_id,name,seasons,matches,goals,birthdate,wikidata_qid,name_wd,birthdate_wd,wikipedia_sv
0,abdoulie-tamba,🇬🇦Abdoulie Tamba,2025,5,0,,NaN,NaN,NaN,NaN
1,alexander-fransson,🇸🇪Alexander Fransson,2013 och 7 säsonger,201,17,,NaN,NaN,NaN,NaN
2,anton-eriksson,🇸🇪Anton Eriksson,"2022, 2023, 2024, 2025",79,0,,NaN,NaN,NaN,NaN
3,axel-bronner,🇸🇪Axel Brönner,2025,16,0,,NaN,NaN,NaN,NaN
4,christoffer-nyman,🇸🇪Christoffer Nyman,2010 och 13 säsonger,329,112,,NaN,NaN,NaN,NaN
5,david-mitov-nilsson,🇸🇪🇲🇰David Mitov Nilsson,2009 och 7 säsonger,136,0,,NaN,NaN,NaN,NaN
6,filip-dagerstal,🇸🇪Filip Dagerstål,2014 och 7 säsonger,143,6,,NaN,NaN,NaN,NaN
7,isak-andri-sigurgeirsson,🇮🇸Isak Andri Sigurgeirsson,"2023, 2024, 2025",60,10,,NaN,NaN,NaN,NaN
8,moutaz-neffati,🇸🇪🇹🇳Moutaz Neffati,"2023, 2024, 2025",45,2,,NaN,NaN,NaN,NaN
9,noel-sernelius,🇸🇪Noel Sernelius,"2023, 2024",3,0,,NaN,NaN,NaN,NaN
10,stephan-bolma,🇬🇭Stephan Bolma,"2023, 2024",5,0,,NaN,NaN,NaN,NaN
11,theo-krantz,🇸🇪Theo Krantz,2025,1,0,,NaN,NaN,NaN,NaN
12,tim-prica,🇸🇪Tim Prica,"2024, 2025",52,6,,NaN,NaN,NaN,NaN
13,ture-sandberg,🇸🇪Ture Sandberg,"2023, 2024",15,1,,NaN,NaN,NaN,NaN
14,ake-andersson,🇸🇪Åke Andersson,"2024, 2025",19,0,,NaN,NaN,NaN,NaN
15,abbas-hassan,🇸🇪🇱🇧Abbas Hassan,"2010, 2011, 2012",32,0,,NaN,NaN,NaN,NaN
16,abderahman-kabous,🇲🇦Abderahman Kabous,2005,18,1,,NaN,NaN,NaN,NaN
17,abdulrazaq-ishaq,🇳🇬Abdulrazaq Ishaq,"2020, 2021, 2022",54,2,,NaN,NaN,NaN,NaN
18,adin-bukva,🇸🇪Adin Bukva,2016,3,0,,NaN,NaN,NaN,NaN
19,alexander-jakobsen,🇩🇰🇪🇬Alexander Jakobsen,"2017, 2018, 2019",42,3,,NaN,NaN,NaN,NaN

In [14]:
def normalize(n):
    return n.lower().replace('"','').strip()

df["name_norm"] = df["name"].apply(normalize)
wd_df["name_norm"] = wd_df["name_wd"].apply(normalize)

merged = df.merge(
    wd_df,
    on="name_norm",
    how="left"
)

In [15]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   snokadb_id    584 non-null    object
 1   name          584 non-null    object
 2   seasons       584 non-null    object
 3   matches       584 non-null    object
 4   goals         584 non-null    object
 5   birthdate     584 non-null    object
 6   name_norm     584 non-null    object
 7   wikidata_qid  0 non-null      object
 8   name_wd       0 non-null      object
 9   birthdate_wd  0 non-null      object
 10  wikipedia_sv  0 non-null      object
dtypes: object(11)
memory usage: 50.3+ KB

In [16]:
final = merged[[
    "snokadb_id",
    "name",
    "wikidata_qid",
    "wikipedia_sv",
    "birthdate_wd"
]]

final.head()

,snokadb_id,name,wikidata_qid,wikipedia_sv,birthdate_wd
0,abdoulie-tamba,🇬🇦Abdoulie Tamba,NaN,NaN,NaN
1,alexander-fransson,🇸🇪Alexander Fransson,NaN,NaN,NaN
2,anton-eriksson,🇸🇪Anton Eriksson,NaN,NaN,NaN
3,axel-bronner,🇸🇪Axel Brönner,NaN,NaN,NaN
4,christoffer-nyman,🇸🇪Christoffer Nyman,NaN,NaN,NaN

In [17]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   snokadb_id    584 non-null    object
 1   name          584 non-null    object
 2   wikidata_qid  0 non-null      object
 3   wikipedia_sv  0 non-null      object
 4   birthdate_wd  0 non-null      object
dtypes: object(5)
memory usage: 22.9+ KB

### Wikipedia / Wikidata 
* [Kategorin har 283](https://sv.wikipedia.org/w/index.php?title=Kategori:Fotbollsspelare_i_IFK_Norrk%C3%B6ping&pagefrom=Nilsson%2C+David+Mitov%0ADavid+Mitov+Nilsson#mw-pages)
* [Wikidata 202](https://w.wiki/Hx5x)

In [18]:
import requests
import time

S = requests.Session()
S.headers.update({
    "User-Agent": "IFK-POC/1.0 (https://github.com/yourrepo; contact: your@email)"
})

URL = "https://sv.wikipedia.org/w/api.php"

def get_category_members():
    members = []
    params = {
        "action": "query",
        "list": "categorymembers",
        "cmtitle": "Kategori:Fotbollsspelare i IFK Norrköping",
        "cmlimit": "500",
        "format": "json",
        "formatversion": "2"
    }

    while True:
        r = S.get(URL, params=params, timeout=30)
        r.raise_for_status()

        # debug om något går fel
        if "application/json" not in r.headers.get("Content-Type", ""):
            print("Fick inte JSON:")
            print(r.text[:500])
            break

        data = r.json()

        members.extend(data["query"]["categorymembers"])

        if "continue" in data:
            params.update(data["continue"])
            time.sleep(0.5)  # snäll mot API:t
        else:
            break

    return [m["title"] for m in members]

titles = get_category_members()
len(titles)

323

In [19]:
#titles

In [20]:
import requests
import time
import pandas as pd

WD_API = "https://www.wikidata.org/w/api.php"

session = requests.Session()
session.headers.update({
    "User-Agent": "IFK-Norrkoping-POC/1.0 (https://github.com/dittrepo; kontakt: salgö60@msn.com)"
})

In [21]:
# slå upp titles 
import requests
import pandas as pd
import time


def lookup_titles_in_batches(titles, batch_size=50):
    results = []

    for i in range(0, len(titles), batch_size):
        batch = titles[i:i+batch_size]
        titles_str = "|".join(batch)

        params = {
            "action": "wbgetentities",
            "sites": "svwiki",
            "titles": titles_str,
            "props": "claims|sitelinks",
            "redirects": "yes",
            "format": "json"
        }
        r = session.get(WD_API, params=params)
        r.raise_for_status()
        data = r.json()

        entities = data.get("entities", {})

        for title in batch:
            qid = None
            birthdate = None
            has_p54 = False

            # hitta rätt entity via sitelink
            for entity in entities.values():
                if entity.get("sitelinks", {}).get("svwiki", {}).get("title") == title:
                    qid = entity.get("id")
                    claims = entity.get("claims", {})

                    # birthdate
                    if "P569" in claims:
                        birthdate = claims["P569"][0]["mainsnak"]["datavalue"]["value"]["time"]

                    # P54 IFK
                    if "P54" in claims:
                        for c in claims["P54"]:
                            target = c["mainsnak"]["datavalue"]["value"]["id"]
                            if target == "Q329607":  # IFK Norrköping
                                has_p54 = True
                    break

            results.append({
                "wikipedia_sv": title,
                "wikidata_qid": qid,
                "birthdate_wd": birthdate,
                "has_P54_IFK": has_p54
            })

        time.sleep(0.5)  # var snäll mot API:t

    return pd.DataFrame(results)

df_wiki = lookup_titles_in_batches(titles)
df_wiki.head()

       wikipedia_sv wikidata_qid           birthdate_wd  has_P54_IFK
0  Ishaq Abdulrazak    Q96361469  +2002-05-05T00:00:00Z         True
1  Samuel Adegbenro    Q19152611  +1995-12-03T00:00:00Z        False
2   Viktor Agardius     Q5543358  +1989-10-23T00:00:00Z        False
3    Enis Ahmetovic    Q19787867  +1992-01-26T00:00:00Z        False
4  Astrit Ajdarević      Q751101  +1990-04-17T00:00:00Z         True

In [22]:
df_wiki.to_csv("ifkwikipedia.csv")

In [23]:
df_wiki["has_P54_IFK"].value_counts()

has_P54_IFK
False    190
True     133
Name: count, dtype: int64

In [24]:
df_wiki.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 323 entries, 0 to 322
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   wikipedia_sv  323 non-null    object
 1   wikidata_qid  323 non-null    object
 2   birthdate_wd  323 non-null    object
 3   has_P54_IFK   323 non-null    bool
dtypes: bool(1), object(3)
memory usage: 8.0+ KB

## Quickstatement   
* new property P14243

In [27]:
qs_rows = []

for _, row in merged.iterrows():
    qid = row["wikidata_qid"]
    
    if isinstance(qid, str) and qid.strip():
        snokadb_id = row["snokadb_id"]
        
        # utan referens
        qs = f'{qid}\tP14243\t"{snokadb_id}"'
        
        qs_rows.append(qs)

# skriv till fil
with open("snokadb_quickstatements.txt", "w", encoding="utf-8") as f:
    for line in qs_rows:
        f.write(line + "\n")

print("QuickStatements-fil skapad: snokadb_quickstatements.txt")
print("\nExempel:")
print("\n".join(qs_rows[:5]))

QuickStatements-fil skapad: snokadb_quickstatements.txt

Exempel:

## Status rapport

In [28]:
import pandas as pd

# Wikipedia-länk
from urllib.parse import quote

df_wiki["wikipedia_url"] = df_wiki["wikipedia_sv"].apply(
    lambda x: "https://sv.wikipedia.org/wiki/" + quote(x.replace(" ", "_"))
)
# Wikidata-länk
df_wiki["wikidata_url"] = "https://www.wikidata.org/wiki/" + df_wiki["wikidata_qid"]

# SnokaDb-länk (matcha på namn)
name_to_slug = dict(zip(df["name"], df["snokadb_id"]))
df_wiki["snokadb_id"] = df_wiki["wikipedia_sv"].map(name_to_slug)
df_wiki["snokadb_url"] = "https://snokadb.se/spelare/" + df_wiki["snokadb_id"].fillna("")

In [29]:
total_snokadb = len(df)
total_wikipedia = len(df_wiki)
total_p54 = df_wiki["has_P54_IFK"].sum()
missing_p54 = total_wikipedia - total_p54

coverage_percent = round((total_p54 / total_wikipedia) * 100, 1)

In [30]:
# ================================
# HÄMTA WIKIDATA P54 – BOIS
# ================================
import requests


SPARQL = """
SELECT ?item ?itemLabel WHERE {
  ?item wdt:P54 wd:Q863273 .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "sv,en,mul" .
  }
}
"""
session = requests.Session()
session.headers.update({
    "User-Agent": "SnokaDB Wikidata research script (salgo60@msn.com)",
    "Accept": "application/sparql-results+json"
})


url = "https://query.wikidata.org/sparql"
response = session.get(url, params={"query": SPARQL}, timeout=30)
response.raise_for_status()
data = response.json()

wd_players = []
for r in data["results"]["bindings"]:
    wd_players.append({
        "qid": r["item"]["value"].split("/")[-1],
        "name": r["itemLabel"]["value"]
    })

print("Wikidata P54 spelare:", len(wd_players))

Wikidata P54 spelare: 281

In [31]:
wd_players

[{'qid': 'Q128845', 'name': 'Lee Baxter'},
 {'qid': 'Q151373', 'name': 'Babis Stefanidis'},
 {'qid': 'Q176721', 'name': 'André Schei Lindbæk'},
 {'qid': 'Q177434', 'name': 'Jörgen Pettersson'},
 {'qid': 'Q195874', 'name': 'Joakim Nilsson'},
 {'qid': 'Q256861', 'name': 'Mikael Dahlgren'},
 {'qid': 'Q278734', 'name': 'Rade Prica'},
 {'qid': 'Q312379', 'name': 'Jonas Olsson'},
 {'qid': 'Q359016', 'name': 'Andreas Dahl'},
 {'qid': 'Q361101', 'name': 'Ajsel Kujović'},
 {'qid': 'Q440904', 'name': 'Rasmus Lindgren'},
 {'qid': 'Q445724', 'name': 'Mats Aronsson'},
 {'qid': 'Q498468', 'name': 'Andreas Jakobsson'},
 {'qid': 'Q501307', 'name': 'Andreas Yngvesson'},
 {'qid': 'Q515599', 'name': 'Viktor Noring'},
 {'qid': 'Q526682', 'name': 'Pontus Farnerud'},
 {'qid': 'Q535027', 'name': 'Jonas Thern'},
 {'qid': 'Q550939', 'name': 'Emir Kujović'},
 {'qid': 'Q587865', 'name': 'Matthias Eklund'},
 {'qid': 'Q596509', 'name': 'Curt Bergsten'},
 {'qid': 'Q604130', 'name': 'Daniel Nannskog'},
 {'qid': 'Q609789', 'name': 'Antti Okkonen'},
 {'qid': 'Q645306', 'name': 'Ivo Pękalski'},
 {'qid': 'Q650989', 'name': 'Indrek Zelinski'},
 {'qid': 'Q679778', 'name': 'Jon Jönsson'},
 {'qid': 'Q706608', 'name': 'Björn Nordqvist'},
 {'qid': 'Q715348', 'name': 'Stuart Baxter'},
 {'qid': 'Q721068', 'name': 'Christopher Sullivan'},
 {'qid': 'Q722261', 'name': 'Sigge Lindberg'},
 {'qid': 'Q722287', 'name': 'Albin Dahl'},
 {'qid': 'Q725952', 'name': 'Jones Kusi-Asare'},
 {'qid': 'Q774885', 'name': 'Johnny Lundberg'},
 {'qid': 'Q921245', 'name': 'Daniel Theorin'},
 {'qid': 'Q939199', 'name': 'Joe Sise'},
 {'qid': 'Q940329', 'name': 'Johan Andersson'},
 {'qid': 'Q944710', 'name': 'Fredrik Svanbäck'},
 {'qid': 'Q958054', 'name': 'Hasan Cetinkaya'},
 {'qid': 'Q973638', 'name': 'Harry Nilsson'},
 {'qid': 'Q1068983', 'name': 'Cheikh Sarr'},
 {'qid': 'Q1094668', 'name': 'Claes Cronqvist'},
 {'qid': 'Q1124734', 'name': 'Jonas Sandqvist'},
 {'qid': 'Q1159011', 'name': 'Dan Brzokoupil'},
 {'qid': 'Q1174137', 'name': 'Valentino Lai'},
 {'qid': 'Q1341836', 'name': 'Alexander Farnerud'},
 {'qid': 'Q1351809', 'name': 'Roger Magnusson'},
 {'qid': 'Q1365474', 'name': 'Kevin Amuneke'},
 {'qid': 'Q1369560', 'name': 'Göran Hagberg'},
 {'qid': 'Q1371164', 'name': 'Jörgen Augustsson'},
 {'qid': 'Q1379017', 'name': 'Joakim Persson'},
 {'qid': 'Q1412855', 'name': 'John Anderberg'},
 {'qid': 'Q1445152', 'name': 'Pär Cederqvist'},
 {'qid': 'Q1674761', 'name': 'Issa Manglind'},
 {'qid': 'Q1730675', 'name': 'Karl Corneliusson'},
 {'qid': 'Q1777645', 'name': 'Knut Hansson'},
 {'qid': 'Q1783788', 'name': 'Pontus Segerström'},
 {'qid': 'Q1789428', 'name': 'Kristoffer Näfver'},
 {'qid': 'Q1827686', 'name': 'Liridon Leçi'},
 {'qid': 'Q1856689', 'name': 'Morten Nielsen'},
 {'qid': 'Q1894253', 'name': 'Marcus Lantz'},
 {'qid': 'Q2057168', 'name': 'Jesper Westerberg'},
 {'qid': 'Q2070000', 'name': 'Per Harrysson'},
 {'qid': 'Q2113100', 'name': 'Darko Lukanović'},
 {'qid': 'Q2161749', 'name': 'Roger Karlsson'},
 {'qid': 'Q2302277', 'name': 'Sonny Johansson'},
 {'qid': 'Q2335944', 'name': 'Stefan Alvén'},
 {'qid': 'Q2481863', 'name': 'Håkan Söderstjerna'},
 {'qid': 'Q2577344', 'name': 'Alagie Sosseh'},
 {'qid': 'Q2824652', 'name': 'Admir Aganović'},
 {'qid': 'Q2909548', 'name': 'Alexander Nilsson'},
 {'qid': 'Q3047223', 'name': 'Edafe Egbedi'},
 {'qid': 'Q3069432', 'name': 'Fernando João Lobo Aguiar'},
 {'qid': 'Q3197112', 'name': 'Kingsley Amuneke'},
 {'qid': 'Q3375080', 'name': 'Mattias Adelstam'},
 {'qid': 'Q3481498', 'name': 'Grétar Ólafur Hjartarson'},
 {'qid': 'Q3606209', 'name': 'Afo Dodoo'},
 {'qid': 'Q3615337', 'name': 'Anders Friberg'},
 {'qid': 'Q3615347', 'name': 'Anders Ljungberg'},
 {'qid': 'Q3624282', 'name': 'Arthur Karlsson'},
 {'qid': 'Q3630924', 'name': 'Auðun Helgason'},
 {'qid': 'Q3678961', 'name': 'Claes Malmberg'},
 {'qid': 'Q3742258', 'name': 'Feliciano Magro'},
 {'qid': 'Q3806302', 'name': 'Jakob Augustsson'},
 {'qid': 'Q3808108', 'name': 'Jesper Ljung'},
 {'qid': 'Q3903445', 'name': 'Pierre Gallo'},
 {'qid': 'Q3916018', 'name': 'Mikael Rynell'},
 {'qid': 'Q4115530', 'name': 'BoBo Bola'},
 {'qid': 'Q4356328', 'name': 'Robin Wikman'},
 {'qid': 'Q4706519', 'name': 'Alan Dodd'},
 {'qid': 'Q4710370', 'name': 'Albert Guðmundsson'},
 {'qid': 'Q4720447', 'name': 'Alexander Zaim'},
 {'qid': 'Q4730939', 'name': 'Allan Ravn'},
 {'qid': 'Q4757595', 'name': 'Andrew Kelly'},
 {'qid': 'Q4895700', 'name': 'Bertil Nilsson'},
 {'qid': 'Q4919755', 'name': 'Björn Nilsson'},
 {'qid': 'Q4994113', 'name': 'Thomas Raun'},
 {'qid': 'Q5109191', 'name': 'Christer Jacobsson'},
 {'qid': 'Q5162084', 'name': 'Conny Rosén'},
 {'qid': 'Q5219536', 'name': 'Danijel Milovanovic'},
 {'qid': 'Q5499492', 'name': 'Fredrik Liverstam'},
 {'qid': 'Q5499507', 'name': 'Fredrik Olsson'},
 {'qid': 'Q5515898', 'name': 'Gabriel Ucar'},
 {'qid': 'Q5553454', 'name': 'Charles Anderson'},
 {'qid': 'Q5555873', 'name': 'Philip Andersson'},
 {'qid': 'Q5560724', 'name': 'Muamet Asanovski'},
 {'qid': 'Q5561255', 'name': 'Jonathan Asp'},
 {'qid': 'Q5562414', 'name': 'Bo Augustsson'},
 {'qid': 'Q5562812', 'name': 'Morten Avnskjold'},
 {'qid': 'Q5563300', 'name': 'Samuel Aziz'},
 {'qid': 'Q5570306', 'name': 'Mikael Bengtsson'},
 {'qid': 'Q5603059', 'name': 'Christoffer Carlsson'},
 {'qid': 'Q5606477', 'name': 'Greger Andrijevski'},
 {'qid': 'Q5621500', 'name': 'Gustavo Papa'},
 {'qid': 'Q5716442', 'name': 'Henrik Nilsson'},
 {'qid': 'Q5755408', 'name': 'Calle Genberg'},
 {'qid': 'Q5812584', 'name': 'Christoffer Tapper Holter'},
 {'qid': 'Q5880275', 'name': 'Daniel Jarl'},
 {'qid': 'Q5881356', 'name': 'Mirza Jelečak'},
 {'qid': 'Q5901356', 'name': 'Fredrik Karlsson'},
 {'qid': 'Q5938939', 'name': 'Tommy Larsson'},
 {'qid': 'Q5956455', 'name': 'Jonas Lindh'},
 {'qid': 'Q5960803', 'name': 'Per-Ola Ljung'},
 {'qid': 'Q5973574', 'name': 'Tobias Malm'},
 {'qid': 'Q5974029', 'name': 'Linus Malmqvist'},
 {'qid': 'Q5982441', 'name': 'Ian Moores'},
 {'qid': 'Q5996278', 'name': 'Amar Muharemovic'},
 {'qid': 'Q6000529', 'name': 'Benny Mårtensson'},
 {'qid': 'Q6000750', 'name': 'Max Mölder'},
 {'qid': 'Q6006723', 'name': 'Alvedin Nezirovac'},
 {'qid': 'Q6007805', 'name': 'Niklas Nielsen'},
 {'qid': 'Q6016460', 'name': 'Johan Norell'},
 {'qid': 'Q6027417', 'name': 'Linus Olsson'},
 {'qid': 'Q6027424', 'name': 'Linus R Olsson'},
 {'qid': 'Q6038360', 'name': 'Dejan Pavlovic'},
 {'qid': 'Q6043074', 'name': 'Johan Persson'},
 {'qid': 'Q6080147', 'name': 'Claes Munck af Rosenschöld'},
 {'qid': 'Q6099222', 'name': 'Ivo Vazgeč'},
 {'qid': 'Q6157036', 'name': 'Rolf Nilsson'},
 {'qid': 'Q6163406', 'name': 'Amethyst Bradley Ralani'},
 {'qid': 'Q6179784', 'name': 'Jens Nordström'},
 {'qid': 'Q6198880', 'name': 'Mats Svensson'},
 {'qid': 'Q6199253', 'name': 'Viktor Svensson'},
 {'qid': 'Q6220036', 'name': 'Mathias Unkuri'},
 {'qid': 'Q6522739', 'name': 'Lennart Hansson'},
 {'qid': 'Q6701612', 'name': 'Luka Mijaljevic'},
 {'qid': 'Q6758145', 'name': 'Marcus Ekheim'},
 {'qid': 'Q6771200', 'name': 'Marko Mugoša'},
 {'qid': 'Q6891440', 'name': 'Mohamed Ramadan'},
 {'qid': 'Q7147943', 'name': 'Patrik Sundström'},
 {'qid': 'Q7360395', 'name': 'Roland Rasmusson'},
 {'qid': 'Q7606118', 'name': 'Stefan Hansson'},
 {'qid': 'Q7784077', 'name': 'Thierry Zahui'},
 {'qid': 'Q8076971', 'name': 'Árni Stefánsson'},
 {'qid': 'Q8465957', 'name': 'Gustaf Crona'},
 {'qid': 'Q10555502', 'name': 'Bahrudin Atajić'},
 {'qid': 'Q10557517', 'name': 'Sonny Karlsson'},
 {'qid': 'Q10621747', 'name': 'Patrik Åström'},
 {'qid': 'Q10680740', 'name': 'Stojan Lukic'},
 {'qid': 'Q12331063', 'name': 'Patrik Johansson'},
 {'qid': 'Q15616315', 'name': 'Filip Sachpekidis'},
 {'qid': 'Q15725598', 'name': 'Hasse Persson'},
 {'qid': 'Q15852223', 'name': 'Urban Stoltz'},
 {'qid': 'Q15917556', 'name': 'Hampus Nilsson'},
 {'qid': 'Q16157810', 'name': 'Erik Andersson'},
 {'qid': 'Q16235695', 'name': 'Sean Okoli'},
 {'qid': 'Q16236454', 'name': 'Filip Pivkovski'},
 {'qid': 'Q16466359', 'name': 'Sadat Karim'},
 {'qid': 'Q16632900', 'name': 'Robin Eliasson Hofsö'},
 {'qid': 'Q16633012', 'name': 'Bill Halvorsen'},
 {'qid': 'Q16633347', 'name': 'Kim Persson'},
 {'qid': 'Q16633383', 'name': 'Martin Rudolfsson'},
 {'qid': 'Q16633396', 'name': 'Niclas Rønne'},
 {'qid': 'Q16633419', 'name': 'Mirza Selimović'},
 {'qid': 'Q16633441', 'name': 'Andrew Stadler'},
 {'qid': 'Q16633492', 'name': 'Per-Åke Theander'},
 {'qid': 'Q16633508', 'name': 'Alexander Tkacz'},
 {'qid': 'Q16633511', 'name': 'Paul Torres'},
 {'qid': 'Q16633519', 'name': 'Niklas Uddenäs'},
 {'qid': 'Q16838141', 'name': 'Harry Dahl'},
 {'qid': 'Q16945498', 'name': 'Monday Samuel'},
 {'qid': 'Q17505123', 'name': 'Göran Petersson'},
 {'qid': 'Q17505172', 'name': 'Kjell Lindstrand'},
 {'qid': 'Q17518783', 'name': 'Leif Carlsen'},
 {'qid': 'Q17560650', 'name': 'Sigvard Petersson'},
 {'qid': 'Q18057108', 'name': 'Tommy Gustafsson'},
 {'qid': 'Q18128125', 'name': 'Jan-Erik Sjöberg'},
 {'qid': 'Q18238570', 'name': 'Måns Ekvall'},
 {'qid': 'Q18392995', 'name': 'Stefan Nilsson'},
 {'qid': 'Q19383001', 'name': 'Nils Westergren'},
 {'qid': 'Q19758568', 'name': 'Rolf Andersson'},
 {'qid': 'Q19787867', 'name': 'Enis Ahmetovic'},
 {'qid': 'Q19787880', 'name': 'Dennis Olofsson'},
 {'qid': 'Q19938340', 'name': 'Igor Arsenijević'},
 {'qid': 'Q19977079', 'name': 'Mårten Nordbeck'},
 {'qid': 'Q24449794', 'name': 'Lukas Sunesson'},
 {'qid': 'Q26262205', 'name': 'Stefan Ilic'},
 {'qid': 'Q26735345', 'name': 'Oskar Sverrisson'},
 {'qid': 'Q26735350', 'name': 'Erik Pärsson'},
 {'qid': 'Q27469945', 'name': 'Saber Azizi'},
 {'qid': 'Q28650130', 'name': 'Edi Sylisufaj'},
 {'qid': 'Q28840127', 'name': 'Noor Zadran'},
 {'qid': 'Q30064081', 'name': 'Melvin Frithzell'},
 {'qid': 'Q30586199', 'name': 'Alfons Sampsted'},
 {'qid': 'Q30612091', 'name': 'Jonathan Levi'},
 {'qid': 'Q42393771', 'name': 'Oscar Petersson'},
 {'qid': 'Q47506164', 'name': 'Nikola Ladan'},
 {'qid': 'Q49104410', 'name': 'Rasmus Alm'},
 {'qid': 'Q56072718', 'name': 'Jetmir Haliti'},
 {'qid': 'Q56072720', 'name': 'Daniel Ask'},
 {'qid': 'Q56072721', 'name': 'Philip Ljung'},
 {'qid': 'Q56072730', 'name': 'Adi Nalic'},
 {'qid': 'Q56241740', 'name': 'Akram Mansour'},
 {'qid': 'Q56241747', 'name': 'Granit Stagova'},
 {'qid': 'Q60823265', 'name': 'Albin Linnér'},
 {'qid': 'Q60841131', 'name': 'Amr Kaddoura'},
 {'qid': 'Q63124032', 'name': 'Philip Mårtensson'},
 {'qid': 'Q63124075', 'name': 'Ismael Diawara'},
 {'qid': 'Q63124078', 'name': 'Rasmus Wiedesheim-Paul'},
 {'qid': 'Q63801141', 'name': 'Edvin Dahlqvist'},
 {'qid': 'Q70251271', 'name': 'Armin Gigovic'},
 {'qid': 'Q74225082', 'name': 'Markus Björkqvist'},
 {'qid': 'Q74295637', 'name': 'Kevin Jensen'},
 {'qid': 'Q96182824', 'name': 'Jacob Ondrejka'},
 {'qid': 'Q96482589', 'name': 'Jakob Andersson'},
 {'qid': 'Q96942955', 'name': 'Mikael Marqués'},
 {'qid': 'Q97982526', 'name': 'Melker Jonsson'},
 {'qid': 'Q104414717', 'name': 'Björn Fure'},
 {'qid': 'Q104437474', 'name': 'Johnny Kongsbøg'},
 {'qid': 'Q106425241', 'name': 'Adam Egnell'},
 {'qid': 'Q106472504', 'name': 'Victor Karlsson'},
 {'qid': 'Q106811202', 'name': 'Lennart Holmqvist'},
 {'qid': 'Q106944019', 'name': 'Unai Veiga'},
 {'qid': 'Q107314474', 'name': 'Filip Olsson'},
 {'qid': 'Q107473526', 'name': 'Patrick Nwadike'},
 {'qid': 'Q108689044', 'name': 'Svante Hildeman'},
 {'qid': 'Q108700292', 'name': 'Johan Rapp'},
 {'qid': 'Q108700707', 'name': 'Melker Heier'},
 {'qid': 'Q110827964', 'name': 'Andreas Murbeck'},
 {'qid': 'Q111838490', 'name': 'Hampus Näsström'},
 {'qid': 'Q112111167', 'name': 'Erik Hedenquist'},
 {'qid': 'Q113496118', 'name': 'David Edvardsson'},
 {'qid': 'Q116807981', 'name': 'Lars Alm'},
 {'qid': 'Q116808239', 'name': 'Knut Almqvist'},
 {'qid': 'Q121913586', 'name': 'Camil Jebara'},
 {'qid': 'Q124542097', 'name': 'Henning Linder'},
 {'qid': 'Q124542114', 'name': 'Nisse Svensson'},
 {'qid': 'Q124542369', 'name': 'John "Tjodde" Nilsson'},
 {'qid': 'Q124542490', 'name': 'Sven Branting'},
 {'qid': 'Q124542499', 'name': 'Axel Johansson'},
 {'qid': 'Q124571282', 'name': 'Helge Jönsson'},
 {'qid': 'Q124575831', 'name': 'Erik Linder'},
 {'qid': 'Q124580313', 'name': 'Carl Hult'},
 {'qid': 'Q124581703', 'name': 'Svante Kvist'},
 {'qid': 'Q124622688', 'name': 'Erik "Tjomme" Persson'},
 {'qid': 'Q124669938', 'name': 'Melker Widell'},
 {'qid': 'Q124827355', 'name': 'Kjell Ekvall'},
 {'qid': 'Q124827435', 'name': 'Gunnar Bergsten'},
 {'qid': 'Q124827699', 'name': 'Tore Ström'},
 {'qid': 'Q124827790', 'name': 'Henning Pettersson'},
 {'qid': 'Q125267936', 'name': 'Gustaf Lundberg'},
 {'qid': 'Q125280585', 'name': 'Erik Pettersson'},
 {'qid': 'Q125282935', 'name': 'Arne Nilsson'},
 {'qid': 'Q125430154', 'name': 'Kofi Asare'},
 {'qid': 'Q126954794', 'name': 'Max Nilsson'},
 {'qid': 'Q130616860', 'name': 'Gent Elezaj'},
 {'qid': 'Q132131087', 'name': 'Bengt Larsson'},
 {'qid': 'Q132396220', 'name': 'Mikael Martinsson'},
 {'qid': 'Q132767654', 'name': 'Kenneth Berg'},
 {'qid': 'Q132774928', 'name': 'Christer Lindgren'},
 {'qid': 'Q132775094', 'name': 'Sven Malmborg'},
 {'qid': 'Q132775165', 'name': 'Dan Mårtensson'},
 {'qid': 'Q132776472', 'name': 'Lars-Ove Nilsson'},
 {'qid': 'Q132776905', 'name': 'Christer Olsson'},
 {'qid': 'Q134711372', 'name': 'Knut Holm'},
 {'qid': 'Q136750533', 'name': 'Constantino Capotondi'},
 {'qid': 'Q136756817', 'name': 'Maxwell Ozoemena'},
 {'qid': 'Q136756954', 'name': "Max'Med Mohamed"},
 {'qid': 'Q136759634', 'name': 'Xavier Odhiambo'},
 {'qid': 'Q136759816', 'name': 'Christian Stark'},
 {'qid': 'Q136760063', 'name': 'Gustaf Westström'},
 {'qid': 'Q136766426', 'name': 'Tobias Karlsson'},
 {'qid': 'Q138818232', 'name': 'Roy Österlund'}]

In [32]:
import requests
import pandas as pd
import mwclient
from datetime import datetime

# =====================================
# 1. HÄMTA WIKIDATA (P54 )
# =====================================

SPARQL = """
SELECT ?player ?playerLabel WHERE {
  ?player wdt:P54 wd:Q329607 .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "sv,en,mul".
  }
}
"""

session = requests.Session()
session.headers.update({
    "User-Agent": "SnokaDB Wikidata research script (salgo60@msn.com)",
    "Accept": "application/sparql-results+json"
})

url = "https://query.wikidata.org/sparql"
response = session.get(url, params={"query": SPARQL}, timeout=30)
response.raise_for_status()
data = response.json()

wd_rows = []
for item in data["results"]["bindings"]:
    wd_rows.append({
        "wikidata_id": item["player"]["value"].split("/")[-1],
        "wd_label": item["playerLabel"]["value"]
    })

df_wd = pd.DataFrame(wd_rows)
wd_qids = set(df_wd["wikidata_id"])

# =====================================
# 2. HÄMTA WIKIPEDIA-KATEGORI
# =====================================

site = mwclient.Site("sv.wikipedia.org")
category = site.categories["Fotbollsspelare i IFK Norrköping"]

def chunked(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]

pages = [p for p in category.members() if p.namespace == 0]
titles = [p.name for p in pages]

wiki_rows = []

for batch in chunked(titles, 50):
    result = site.api(
        action="query",
        titles="|".join(batch),
        prop="pageprops",
        ppprop="wikibase_item",
        format="json"
    )
    for page in result["query"]["pages"].values():
        wiki_rows.append({
            "wiki_name": page.get("title"),
            "wikidata_id": page.get("pageprops", {}).get("wikibase_item")
        })

df_wiki = pd.DataFrame(wiki_rows)

wiki_titles = list(df_wiki["wiki_name"])
wiki_qids = dict(zip(df_wiki["wiki_name"], df_wiki["wikidata_id"]))

wiki_with_p54 = {
    title for title in wiki_titles
    if wiki_qids.get(title) in wd_qids
}

wiki_without_p54 = [
    title for title in wiki_titles
    if wiki_qids.get(title) not in wd_qids
]

# =====================================
# 3. NYCKELTAL
# =====================================

total_wiki = len(wiki_titles)
total_p54 = len(wd_qids)
missing_p54 = len(wiki_without_p54)
coverage_percent = round((len(wiki_with_p54) / total_wiki) * 100, 1) if total_wiki else 0

# =====================================
# 4. BYGG HTML-RAPPORT
# =====================================

html = f"""
<html>
<head>
<meta charset="utf-8">
<title>Statusrapport AIK – Wikipedia / Wikidata</title>
<style>
body {{ font-family: Arial, sans-serif; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border: 1px solid #ccc; padding: 6px; }}
th {{ background-color: #f2f2f2; }}
.bad {{ background-color: #ffe6e6; }}
.good {{ background-color: #e6ffe6; }}
</style>
</head>
<body>

<h1>Statusrapport AIK – Wikipedia / Wikidata</h1>
<p>Genererad: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>

<h2>Nyckeltal</h2>
<ul>
<li>Wikipedia-kategori: {total_wiki} spelare</li>
<li>Wikidata P54 AIK: {total_p54} spelare</li>
<li>Wikipedia-artiklar utan P54: {missing_p54}</li>
<li>Täckning (Wikipedia → WD P54): {coverage_percent} %</li>
</ul>

<hr>

<h2>Wikipedia-kategori – Identifieringsstatus</h2>

<table>
<tr>
<th>Spelare</th>
<th>Wikidata</th>
<th>P54</th>
</tr>
"""

# Sortera så ❌ kommer först
sorted_titles = sorted(
    wiki_titles,
    key=lambda t: t in wiki_with_p54
)

for title in sorted_titles:
    wiki_link = f'<a href="https://sv.wikipedia.org/wiki/{title.replace(" ", "_")}" target="_blank">{title}</a>'
    
    qid = wiki_qids.get(title)
    
    if qid:
        wd_link = f'<a href="https://www.wikidata.org/wiki/{qid}" target="_blank">{qid}</a>'
        has_p54 = qid in wd_qids
    else:
        wd_link = "–"
        has_p54 = False
    
    status = "✅" if has_p54 else "❌"
    row_class = "good" if has_p54 else "bad"
    
    html += f"""
    <tr class="{row_class}">
        <td>{wiki_link}</td>
        <td>{wd_link}</td>
        <td>{status}</td>
    </tr>
    """

html += """
</table>
</body>
</html>
"""
from datetime import datetime

today_str = datetime.now().strftime("%Y%m%d")
output_file = f"snokadb_statusrapport_{today_str}.html"

with open(output_file, "w", encoding="utf-8") as f:
    f.write(html)

print("Rapport skapad:", output_file)

Rapport skapad: snokadb_statusrapport_20260329.html

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   snokadb_id  584 non-null    object
 1   name        584 non-null    object
 2   seasons     584 non-null    object
 3   matches     584 non-null    object
 4   goals       584 non-null    object
 5   birthdate   584 non-null    object
 6   name_norm   584 non-null    object
dtypes: object(7)
memory usage: 32.1+ KB

0
1
2
3
4
      ..
579
580
581
582
583
Name: birthdate, Length: 584, dtype: object

## MixandMatch  
id,name,desc,type,url,wikidata

In [37]:
import pandas as pd

def build_mixnmatch(df):
    rows = []

    for _, row in df.iterrows():
        snokadb_id = str(row["snokadb_id"])
        name = row["name"]
        birthdate = row.get("birthdate", "")
        seasons = row.get("seasons", "")
        matches = row.get("matches", "")
        goals = row.get("goals", "")
        qid = row.get("wikidata_qid", "")

        # beskrivning
        desc_parts = ["Swedish association football player"]

        if seasons:
            desc_parts.append(f"played seasons {seasons}")
        if matches:
            desc_parts.append(f"{matches} matches")
        if goals:
            desc_parts.append(f"{goals} goals")
        if birthdate:
            desc_parts.append(f"born {birthdate}")

        desc = ", ".join(desc_parts)

        url = f"https://snokadb.se/spelare/{snokadb_id}"

        rows.append({
            "id": snokadb_id,
            "name": name,
            "desc": desc,
            "type": "Q5",
            "url": url,
            "wikidata": qid if isinstance(qid, str) else ""
        })

    return pd.DataFrame(rows)

In [42]:
mnm_df = build_mixnmatch(df) 
def remove_flags(text):
    return re.sub(r'[\U0001F1E6-\U0001F1FF]{2}', '', text).strip()

mnm_df["name"] = mnm_df["name"].str.replace(
    r'[\U0001F1E6-\U0001F1FF]{2}', '', regex=True
).str.strip() 

#mnm_df["name"] = mnm_df["name"].apply(remove_flags)
from datetime import datetime

# skapa datumsträng
today_str = datetime.now().strftime("%Y%m%d")

filename = f"snokadb_mixnmatch_{today_str}.csv"

mnm_df.to_csv(filename, index=False)

print("Sparad fil:", filename)
mnm_df.head()

Sparad fil: snokadb_mixnmatch_20260329.csv

,id,name,desc,type,url,wikidata
0,abdoulie-tamba,Abdoulie Tamba,"Swedish association football player, played se...",Q5,https://snokadb.se/spelare/abdoulie-tamba,
1,alexander-fransson,Alexander Fransson,"Swedish association football player, played se...",Q5,https://snokadb.se/spelare/alexander-fransson,
2,anton-eriksson,Anton Eriksson,"Swedish association football player, played se...",Q5,https://snokadb.se/spelare/anton-eriksson,
3,axel-bronner,Axel Brönner,"Swedish association football player, played se...",Q5,https://snokadb.se/spelare/axel-bronner,
4,christoffer-nyman,Christoffer Nyman,"Swedish association football player, played se...",Q5,https://snokadb.se/spelare/christoffer-nyman,

In [35]:
from datetime import datetime
end_time = datetime.now()

duration = end_time - start_time

print("\n===== Körningsrapport =====")
print("Starttid :", start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("Sluttid  :", end_time.strftime("%Y-%m-%d %H:%M:%S"))

total_seconds = int(duration.total_seconds())
hours = total_seconds // 3600
minutes = (total_seconds % 3600) // 60
seconds = total_seconds % 60

print(f"Körtid   : {hours}h {minutes}m {seconds}s")
print("===========================\n")

===== Körningsrapport =====
Starttid : 2026-03-29 07:22:57
Sluttid  : 2026-03-29 07:31:42
Körtid   : 0h 8m 44s
===========================