* Denna Notebook [26_aikstats.ipynb](https://github.com/salgo60/ifkdb/blob/main/Notebook/26_aikstats.ipynb)
* [#26](https://github.com/salgo60/ifkdb/issues/26)
   * AIK egenskap [Property:P14202](https://www.wikidata.org/wiki/Property:P14202) 

* AIK
   * sv:Wikipedia [Kategori:Fotbollsspelare_i_AIK](https://sv.wikipedia.org/wiki/Kategori:Fotbollsspelare_i_AIK)
   * https://www.aikstats.se/player.php
   * Wikidata SPARQL https://w.wiki/J3Rk
   * FB https://www.facebook.com/AIKStatistikdatabas/

In [1]:
from datetime import datetime
start_time  = datetime.now()
print("Last run: ", start_time)

Last run:  2026-03-27 20:06:26.293548

In [2]:
import requests
import urllib3

print("requests:", requests.__version__)
print("urllib3:", urllib3.__version__)

requests: 2.32.5
urllib3: 2.6.3

In [3]:
# If needed:
# !pip install requests beautifulsoup4 pandas lxml mwclient tqdm rapidfuzz

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from tqdm import tqdm
from rapidfuzz import fuzz, process
import mwclient

In [4]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

BASE_URL = "https://www.aikstats.se/player.php?who=all"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (research bot; contact: salgo60@msn.com)"
}

response = requests.get(BASE_URL, headers=HEADERS, timeout=20)
response.raise_for_status()

soup = BeautifulSoup(response.text, "lxml")

players = []

for row in soup.find_all("tr", class_="normal"):
    cols = row.find_all("td")
    if len(cols) < 4:
        continue

    link = cols[0].find("a", href=True)
    if not link:
        continue

    name = link.get_text(strip=True)
    href = link["href"]

    try:
        pid = int(href.split("id=")[1])
    except:
        continue

    position = cols[1].get_text(strip=True)
    years = cols[2].get_text(strip=True)
    matches = cols[3].get_text(strip=True)

    players.append({
        "id": pid,
        "name": name,
        "position": position,
        "years_active": years,
        "matches": matches
    })

df = pd.DataFrame(players)

print(f"Hittade {len(df)} spelare")
df.head()

Hittade 1307 spelare

    id                         name     position years_active matches
0    4        Per "Pertan" Karlsson         Back    1998-2022     531
1    8   Daniel "Tjerna" Tjernström  Mittfältare    1999-2013     481
2  200  Nils-Eric "Nisse" Johansson         Back    1997-2018     450
3  543        Sven "Dala" Dahlkvist    Innerback    1974-1987     356
4  270       Gustav "Gurra" Sjöberg      Målvakt    1929-1950     347

In [6]:
df_aik = pd.DataFrame(players)
df_aik.head()

    id                         name     position years_active matches
0    4        Per "Pertan" Karlsson         Back    1998-2022     531
1    8   Daniel "Tjerna" Tjernström  Mittfältare    1999-2013     481
2  200  Nils-Eric "Nisse" Johansson         Back    1997-2018     450
3  543        Sven "Dala" Dahlkvist    Innerback    1974-1987     356
4  270       Gustav "Gurra" Sjöberg      Målvakt    1929-1950     347

In [7]:
def chunked(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size] 
        
import mwclient
import pandas as pd

site = mwclient.Site("sv.wikipedia.org")

category = site.categories["Fotbollsspelare i AIK"]

rows = []

pages = [p for p in category.members() if p.namespace == 0]
titles = [p.name for p in pages]

for batch in chunked(titles, 50):
    result = site.api(
        action="query",
        titles="|".join(batch),
        prop="pageprops",
        ppprop="wikibase_item",
        format="json"
    )

    for page in result["query"]["pages"].values():
        rows.append({
            "wiki_name": page.get("title"),
            "wikidata_id": page.get("pageprops", {}).get("wikibase_item")
        })

df_wiki = pd.DataFrame(rows)

print(f"Hittade {len(df_wiki)} Wikipedia-spelare")
df_wiki.head()

Hittade 447 Wikipedia-spelare

                          wiki_name wikidata_id
0                     Abdihakin Ali  Q119509691
1                       Amin Affane     Q795483
2                       Ammar Ahmed   Q19724740
3  Anders Almgren (fotbollsspelare)     Q182613
4                       Andreas Alm     Q495742

In [8]:
import requests
import pandas as pd

SPARQL = """
SELECT ?player ?playerLabel ?birthDate WHERE {
  ?player wdt:P54 wd:Q221602 .
  OPTIONAL { ?player wdt:P569 ?birthDate. }
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "sv,en,mul".
  }
}
"""

session = requests.Session()
session.headers.update({
    "User-Agent": "AIKStats research script (salgo60@msn.com)",
    "Accept": "application/sparql-results+json"
})

url = "https://query.wikidata.org/sparql"

response = session.get(
    url,
    params={"query": SPARQL},
    timeout=30
)

response.raise_for_status()
data = response.json()

wikidata_players = []

for r in data["results"]["bindings"]:
    wikidata_players.append({
        "wikidata_uri": r["player"]["value"],
        "name": r["playerLabel"]["value"],
        "birthDate": r.get("birthDate", {}).get("value")
    })

df_wd = pd.DataFrame(wikidata_players)
df_wd["wikidata_id"] = df_wd["wikidata_uri"].str.extract(r"(Q\d+)")
df_wd["wikidata_url"] = "https://www.wikidata.org/wiki/" + df_wd["wikidata_id"]
print(f"Wikidata P54 AIK: {len(df_wd)}")
df_wd.head()

Wikidata P54 AIK: 548

,wikidata_uri,name,birthDate,wikidata_id,wikidata_url
0,http://www.wikidata.org/entity/Q6107684,Samuel Ayorinde,1974-10-20T00:00:00Z,Q6107684,https://www.wikidata.org/wiki/Q6107684
1,http://www.wikidata.org/entity/Q6125278,Jakob Haugaard,1992-05-01T00:00:00Z,Q6125278,https://www.wikidata.org/wiki/Q6125278
2,http://www.wikidata.org/entity/Q6169170,Ulf Schramm,1936-11-12T00:00:00Z,Q6169170,https://www.wikidata.org/wiki/Q6169170
3,http://www.wikidata.org/entity/Q6209496,Mikael Thorstensson,1985-01-25T00:00:00Z,Q6209496,https://www.wikidata.org/wiki/Q6209496
4,http://www.wikidata.org/entity/Q6210128,Mattias Thylander,1974-10-22T00:00:00Z,Q6210128,https://www.wikidata.org/wiki/Q6210128

In [9]:
# Wikipedia katergorier   
df_wiki.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 447 entries, 0 to 446
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   wiki_name    447 non-null    object
 1   wikidata_id  447 non-null    object
dtypes: object(2)
memory usage: 7.1+ KB

In [10]:

print(f"AIKStats spelare: {len(df_aik )}")
df_aik.head()

AIKStats spelare: 1307

    id                         name     position years_active matches
0    4        Per "Pertan" Karlsson         Back    1998-2022     531
1    8   Daniel "Tjerna" Tjernström  Mittfältare    1999-2013     481
2  200  Nils-Eric "Nisse" Johansson         Back    1997-2018     450
3  543        Sven "Dala" Dahlkvist    Innerback    1974-1987     356
4  270       Gustav "Gurra" Sjöberg      Målvakt    1929-1950     347

In [11]:
df_aik.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1307 entries, 0 to 1306
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1307 non-null   int64
 1   name          1307 non-null   object
 2   position      1307 non-null   object
 3   years_active  1307 non-null   object
 4   matches       1307 non-null   object
dtypes: int64(1), object(4)
memory usage: 51.2+ KB

In [12]:
wd_set = set(df_wd["wikidata_id"].dropna()) 
wiki_set = set(df_wiki["wikidata_id"].dropna())
wd_not_wiki = wd_set - wiki_set
print("WD men ej Wikipedia:", len(wd_not_wiki))

WD men ej Wikipedia: 102

In [13]:
# Wikipedia men ej WD: 
df_wd[df_wd["wikidata_id"].isin(wd_not_wiki)]

,wikidata_uri,name,birthDate,wikidata_id,wikidata_url
9,http://www.wikidata.org/entity/Q6522719,Lennart Askinger,1922-05-03T00:00:00Z,Q6522719,https://www.wikidata.org/wiki/Q6522719
10,http://www.wikidata.org/entity/Q6771465,Markus Karlsson,1979-12-13T00:00:00Z,Q6771465,https://www.wikidata.org/wiki/Q6771465
11,http://www.wikidata.org/entity/Q7943793,Vyacheslav Jevtushenko,1981-07-26T00:00:00Z,Q7943793,https://www.wikidata.org/wiki/Q7943793
32,http://www.wikidata.org/entity/Q16738032,Georg Kraemer,1925-06-20T00:00:00Z,Q16738032,https://www.wikidata.org/wiki/Q16738032
40,http://www.wikidata.org/entity/Q18045184,Hans Nilsson,1941-11-07T00:00:00Z,Q18045184,https://www.wikidata.org/wiki/Q18045184
...,...,...,...,...,...
533,http://www.wikidata.org/entity/Q133247102,Hernando L'Abbe,1970-02-13T00:00:00Z,Q133247102,https://www.wikidata.org/wiki/Q133247102
534,http://www.wikidata.org/entity/Q133247444,Mattias Gillhart,1974-03-05T00:00:00Z,Q133247444,https://www.wikidata.org/wiki/Q133247444
535,http://www.wikidata.org/entity/Q133247529,David Nildén,1973-02-08T00:00:00Z,Q133247529,https://www.wikidata.org/wiki/Q133247529
536,http://www.wikidata.org/entity/Q133282552,Björn Rydberg,1973-01-01T00:00:00Z,Q133282552,https://www.wikidata.org/wiki/Q133282552
537,http://www.wikidata.org/entity/Q133794590,Stephan Johansson,1975-01-21T00:00:00Z,Q133794590,https://www.wikidata.org/wiki/Q133794590

In [14]:
# jämför mot AIKStats 
import unicodedata
import re

def normalize(name):
    if not name:
        return None

    # Ta bort smeknamn i citationstecken
    name = re.sub(r'".*?"', '', name)

    # Unicode-normalisering
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode()

    # Ta bort skiljetecken
    name = re.sub(r"[^\w\s-]", "", name)

    # Normalisera bindestreck
    name = name.replace("-", " ")

    # Normalisera whitespace
    name = re.sub(r"\s+", " ", name)

    return name.lower().strip()

df_aik["norm_name"] = df_aik["name"].apply(normalize)
df_wd["norm_name"] = df_wd["name"].apply(normalize)

stats_set = set(df_aik["norm_name"].dropna())
wd_name_set = set(df_wd["norm_name"].dropna())

print("WD men ej AIKStats:", len(wd_name_set - stats_set))
print("AIKStats men ej WD:", len(stats_set - wd_name_set))

WD men ej AIKStats: 103
AIKStats men ej WD: 851

In [15]:
df_wd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 548 entries, 0 to 547
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   wikidata_uri  548 non-null    object
 1   name          548 non-null    object
 2   birthDate     547 non-null    object
 3   wikidata_id   548 non-null    object
 4   wikidata_url  548 non-null    object
 5   norm_name     548 non-null    object
dtypes: object(6)
memory usage: 25.8+ KB

In [16]:
df_aik["norm_name"] = df_aik["name"].apply(normalize)
df_wd["norm_name"] = df_wd["name"].apply(normalize)

df_wd["birth_year"] = pd.to_datetime(df_wd["birthDate"], errors="coerce").dt.year

In [17]:
exact_matches = df_aik.merge(
    df_wd,
    on="norm_name",
    how="inner",
    suffixes=("_aik", "_wd")
)

len_exact = len(exact_matches)
print("Exakta matchningar:", len_exact)

Exakta matchningar: 455

In [18]:
matched_names = set(exact_matches["norm_name"])

aik_unmatched = df_aik[~df_aik["norm_name"].isin(matched_names)]
wd_unmatched = df_wd[~df_wd["norm_name"].isin(matched_names)]

print("AIKStats utan WD:", len(aik_unmatched))
print("WD utan AIKStats:", len(wd_unmatched))

AIKStats utan WD: 854
WD utan AIKStats: 103

In [19]:
def lastname(name):
    if not name:
        return None
    return name.split()[-1]

df_aik["lastname"] = df_aik["norm_name"].apply(lastname)
df_wd["lastname"] = df_wd["norm_name"].apply(lastname)

lastname_matches = df_aik.merge(
    df_wd,
    on="lastname",
    how="inner"
)

In [20]:
total_aik = len(df_aik)
total_wd = df_wd["name"].nunique()
matched = len_exact
missing_in_wd = total_aik - matched
wd_extra = total_wd - matched

report = {
    "AIKStats total IDs": total_aik,
    "Wikidata AIK Fotboll objects": total_wd,
    "Exact matches": matched,
    "AIKStats missing in WD": missing_in_wd,
    "WD objects not in AIKStats": wd_extra,
    "Coverage %": round((matched / total_aik) * 100, 2)
}

report

{'AIKStats total IDs': 1307,
 'Wikidata AIK Fotboll objects': 547,
 'Exact matches': 455,
 'AIKStats missing in WD': 852,
 'WD objects not in AIKStats': 92,
 'Coverage %': 34.81}

### Skapa final och rapport

In [22]:
df_final = df_aik.merge(
    df_wd,
    on="norm_name",
    how="inner",
    suffixes=("_aik", "_wd")
) 

print("Matchade rader:", len(df_final))
df_final.head()

Matchade rader: 455

,id,name_aik,position,years_active,matches,norm_name,lastname_aik,wikidata_uri,name_wd,birthDate,wikidata_id,wikidata_url,birth_year,lastname_wd
0,4,"Per ""Pertan"" Karlsson",Back,1998-2022,531,per karlsson,karlsson,http://www.wikidata.org/entity/Q205479,Per Karlsson,1986-01-02T00:00:00Z,Q205479,https://www.wikidata.org/wiki/Q205479,1986.0,karlsson
1,8,"Daniel ""Tjerna"" Tjernström",Mittfältare,1999-2013,481,daniel tjernstrom,tjernstrom,http://www.wikidata.org/entity/Q1162941,Daniel Tjernström,1974-02-19T00:00:00Z,Q1162941,https://www.wikidata.org/wiki/Q1162941,1974.0,tjernstrom
2,200,"Nils-Eric ""Nisse"" Johansson",Back,1997-2018,450,nils eric johansson,johansson,http://www.wikidata.org/entity/Q699824,Nils-Eric Johansson,1980-01-13T00:00:00Z,Q699824,https://www.wikidata.org/wiki/Q699824,1980.0,johansson
3,543,"Sven ""Dala"" Dahlkvist",Innerback,1974-1987,356,sven dahlkvist,dahlkvist,http://www.wikidata.org/entity/Q1368236,Sven Dahlkvist,1955-05-30T00:00:00Z,Q1368236,https://www.wikidata.org/wiki/Q1368236,1955.0,dahlkvist
4,270,"Gustav ""Gurra"" Sjöberg",Målvakt,1929-1950,347,gustav sjoberg,sjoberg,http://www.wikidata.org/entity/Q1369574,Gustav Sjöberg,1913-03-23T00:00:00Z,Q1369574,https://www.wikidata.org/wiki/Q1369574,1913.0,sjoberg

In [23]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455 entries, 0 to 454
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            455 non-null    int64
 1   name_aik      455 non-null    object
 2   position      455 non-null    object
 3   years_active  455 non-null    object
 4   matches       455 non-null    object
 5   norm_name     455 non-null    object
 6   lastname_aik  455 non-null    object
 7   wikidata_uri  455 non-null    object
 8   name_wd       455 non-null    object
 9   birthDate     455 non-null    object
 10  wikidata_id   455 non-null    object
 11  wikidata_url  455 non-null    object
 12  birth_year    455 non-null    float64
 13  lastname_wd   455 non-null    object
dtypes: float64(1), int64(1), object(12)
memory usage: 49.9+ KB

In [25]:
df_merged = df_aik.merge(
    df_wd,
    on="norm_name",
    how="outer",
    indicator=True,
    suffixes=("_aik", "_wd")
) 
print("Rader:", len(df_merged))
df_merged.head()

Rader: 1412

,id,name_aik,position,years_active,matches,norm_name,lastname_aik,wikidata_uri,name_wd,birthDate,wikidata_id,wikidata_url,birth_year,lastname_wd,_merge
0,720.0,A Tilbom,,? - ?,1,a tilbom,tilbom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,NaN,NaN,NaN,NaN,NaN,aaron stoch rydell,NaN,http://www.wikidata.org/entity/Q125506161,Aaron Stoch Rydell,2006-10-14T00:00:00Z,Q125506161,https://www.wikidata.org/wiki/Q125506161,2006.0,rydell,right_only
2,1052.0,Abdi Yusuf,,? - ?,,abdi yusuf,yusuf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,1313.0,Abdihakin Ali,Mittfältare,2012-2022,11,abdihakin ali,ali,http://www.wikidata.org/entity/Q119509691,Abdihakin Ali,2002-01-22T00:00:00Z,Q119509691,https://www.wikidata.org/wiki/Q119509691,2002.0,ali,both
4,1096.0,Abdou-Fatawou Dodja,Forward,? - ?,,abdou fatawou dodja,dodja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [29]:
df_merged["_merge"].value_counts()

_merge
left_only     854
both          455
right_only    103
Name: count, dtype: int64

In [30]:
df_final = df_merged[df_merged["_merge"] == "both"].copy()

In [31]:
df_aik_only = df_merged[df_merged["_merge"] == "left_only"]
df_wd_only = df_merged[df_merged["_merge"] == "right_only"]

In [32]:
report = {
    "AIKStats total IDs": len(df_aik),
    "Wikidata AIK Fotboll objects": df_wd["wikidata_id"].nunique(),
    "Exact matches": len(df_final),
    "AIKStats missing in WD": len(df_aik_only),
    "WD objects not in AIKStats": len(df_wd_only),
    "Coverage %": round((len(df_final) / len(df_aik)) * 100, 2)
}

report

{'AIKStats total IDs': 1307,
 'Wikidata AIK Fotboll objects': 548,
 'Exact matches': 455,
 'AIKStats missing in WD': 854,
 'WD objects not in AIKStats': 103,
 'Coverage %': 34.81}

In [ ]:
# Om > 0 → du har namn-kollisioner (vanligt med t.ex. "Bo Andersson").
df_merged["norm_name"].duplicated().sum()

In [ ]:
df_merged.info()

In [ ]:
import urllib.parse
import pandas as pd

def link_aik(id_value):
    if pd.isna(id_value):
        return ""
    id_int = int(id_value)
    return f"[{id_int}](https://www.aikstats.se/player.php?id={id_int})"

def link_wikidata(qid):
    if pd.isna(qid):
        return ""
    return f"[{qid}](https://www.wikidata.org/wiki/{qid})"

def link_svwiki(name):
    if pd.isna(name):
        return ""
    encoded = urllib.parse.quote(name.replace(" ", "_"))
    return f"[{name}](https://sv.wikipedia.org/wiki/{encoded})"

In [ ]:
df_table = df_merged[df_merged["_merge"] == "both"].copy()

rows = []
rows.append("| Namn | AIK fotboll | Wikidata | Wikipedia |")
rows.append("|------|--------------|----------|------------|")

for _, row in df_table.iterrows():
    namn = row["name_aik"]
    aik_link = link_aik(row["id"])
    wd_link = link_wikidata(row["wikidata_id"])
    wiki_link = link_svwiki(row["name_wd"])

    rows.append(f"| {namn} | {aik_link} | {wd_link} | {wiki_link} |")

markdown_output = "\n".join(rows)

print(markdown_output)

## Quickstatement

In [24]:
qs_lines = []

for _, row in df_final.iterrows():
    qid = row["wikidata_id"]
    value = str(int(row["id"]))  # säkerställ string
    
    line = f'{qid}|P14202|"{value}"'
    qs_lines.append(line)

qs_text = "\n".join(qs_lines)

# spara till fil
with open("quickstatements_p14202.txt", "w") as f:
    f.write(qs_text)

qs_text[:1000]  # preview

'Q205479|P14202|"4"\nQ1162941|P14202|"8"\nQ699824|P14202|"200"\nQ1368236|P14202|"543"\nQ1369574|P14202|"270"\nQ1417354|P14202|"535"\nQ1455128|P14202|"59"\nQ372336|P14202|"1078"\nQ465704|P14202|"610"\nQ768739|P14202|"299"\nQ879659|P14202|"198"\nQ1115797|P14202|"255"\nQ1370473|P14202|"12"\nQ442641|P14202|"63"\nQ246944|P14202|"427"\nQ1727956|P14202|"184"\nQ1375621|P14202|"304"\nQ1909061|P14202|"22"\nQ1184663|P14202|"1103"\nQ937989|P14202|"284"\nQ826876|P14202|"571"\nQ2117450|P14202|"987"\nQ722800|P14202|"455"\nQ2042250|P14202|"552"\nQ5603309|P14202|"332"\nQ1370058|P14202|"217"\nQ2735478|P14202|"840"\nQ1383089|P14202|"188"\nQ182466|P14202|"1"\nQ78787302|P14202|"575"\nQ5942518|P14202|"179"\nQ126483139|P14202|"358"\nQ15965281|P14202|"276"\nQ15663340|P14202|"1168"\nQ1741459|P14202|"592"\nQ973638|P14202|"326"\nQ6009719|P14202|"269"\nQ349848|P14202|"5"\nQ1679885|P14202|"637"\nQ83638|P14202|"1207"\nQ16029847|P14202|"1077"\nQ922597|P14202|"205"\nQ1689176|P14202|"441"\nQ52816724|P14202|"1218"\nQ1161135|P14202|"27"\nQ1689448|P14202|"15"\nQ15594'

### MixandMatch

* [#43](https://github.com/salgo60/ifkdb/issues/43) Problem med tomma poster
  * måste kolla sidan efter "Det finns ingen spelare med det angivna identifikationsnumret"

In [44]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 455 entries, 3 to 1410
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            455 non-null    float64
 1   name_aik      455 non-null    object
 2   position      455 non-null    object
 3   years_active  455 non-null    object
 4   matches       455 non-null    object
 5   norm_name     455 non-null    object
 6   lastname_aik  455 non-null    object
 7   wikidata_uri  455 non-null    object
 8   name_wd       455 non-null    object
 9   birthDate     455 non-null    object
 10  wikidata_id   455 non-null    object
 11  wikidata_url  455 non-null    object
 12  birth_year    455 non-null    float64
 13  lastname_wd   455 non-null    object
 14  _merge        455 non-null    category
dtypes: category(1), float64(2), object(12)
memory usage: 53.9+ KB

In [37]:
df_aik.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1307 entries, 0 to 1306
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1307 non-null   int64
 1   name          1307 non-null   object
 2   position      1307 non-null   object
 3   years_active  1307 non-null   object
 4   matches       1307 non-null   object
 5   norm_name     1307 non-null   object
 6   lastname      1307 non-null   object
dtypes: int64(1), object(6)
memory usage: 71.6+ KB

In [38]:
df_aik.head()

,id,name,position,years_active,matches,norm_name,lastname
0,4,"Per ""Pertan"" Karlsson",Back,1998-2022,531,per karlsson,karlsson
1,8,"Daniel ""Tjerna"" Tjernström",Mittfältare,1999-2013,481,daniel tjernstrom,tjernstrom
2,200,"Nils-Eric ""Nisse"" Johansson",Back,1997-2018,450,nils eric johansson,johansson
3,543,"Sven ""Dala"" Dahlkvist",Innerback,1974-1987,356,sven dahlkvist,dahlkvist
4,270,"Gustav ""Gurra"" Sjöberg",Målvakt,1929-1950,347,gustav sjoberg,sjoberg

In [40]:
df_merged = df_aik.merge(
    df_final[["norm_name", "wikidata_id"]],
    on="norm_name",
    how="left"
)

df_merged.head()

,id,name,position,years_active,matches,norm_name,lastname,wikidata_id
0,4,"Per ""Pertan"" Karlsson",Back,1998-2022,531,per karlsson,karlsson,Q205479
1,8,"Daniel ""Tjerna"" Tjernström",Mittfältare,1999-2013,481,daniel tjernstrom,tjernstrom,Q1162941
2,200,"Nils-Eric ""Nisse"" Johansson",Back,1997-2018,450,nils eric johansson,johansson,Q699824
3,543,"Sven ""Dala"" Dahlkvist",Innerback,1974-1987,356,sven dahlkvist,dahlkvist,Q1368236
4,270,"Gustav ""Gurra"" Sjöberg",Målvakt,1929-1950,347,gustav sjoberg,sjoberg,Q1369574

In [45]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1335 entries, 0 to 1334
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1335 non-null   int64
 1   name          1335 non-null   object
 2   position      1335 non-null   object
 3   years_active  1335 non-null   object
 4   matches       1335 non-null   object
 5   norm_name     1335 non-null   object
 6   lastname      1335 non-null   object
 7   wikidata_id   481 non-null    object
dtypes: int64(1), object(7)
memory usage: 83.6+ KB

In [41]:
import csv

rows = []

for _, row in df_merged.iterrows():
    ext_id = str(int(row["id"]))
    name = row["name"].strip()
    
    desc = f"Swedish association football player, played for AIK, {row['position']}, active {row['years_active']}"
    
    type_qid = "Q5"
    url = f"https://www.aikstats.se/player.php?id={ext_id}"
    
    qid = row["wikidata_id"] if pd.notna(row["wikidata_id"]) else ""
    
    rows.append([ext_id, name, desc, type_qid, url, qid])

with open("aikstats_mixnmatch_with_wd.csv", "w", encoding="utf-8", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["id", "name", "desc", "type", "url", "wikidata"])
    writer.writerows(rows)

print("Klar med Wikidata-kolumn!")

Klar med Wikidata-kolumn!

In [42]:
from datetime import datetime
end_time = datetime.now()

duration = end_time - start_time

print("\n===== Körningsrapport =====")
print("Starttid :", start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("Sluttid  :", end_time.strftime("%Y-%m-%d %H:%M:%S"))

total_seconds = int(duration.total_seconds())
hours = total_seconds // 3600
minutes = (total_seconds % 3600) // 60
seconds = total_seconds % 60

print(f"Körtid   : {hours}h {minutes}m {seconds}s")
print("===========================\n")

===== Körningsrapport =====
Starttid : 2026-03-27 20:06:26
Sluttid  : 2026-03-27 22:00:38
Körtid   : 1h 54m 12s
===========================

In [46]:
import requests

def valid_player(id_):
    url = f"https://www.aikstats.se/player.php?id={id_}"
    r = requests.get(url)
    return "ingen spelare" not in r.text.lower()

df_clean = df_merged[df_merged["id"].apply(valid_player)]

In [47]:
len(df_clean)

1270

In [48]:
len(df_merged)

1335

In [50]:
diff_merge = df_merged.merge(df_clean, how="left", indicator=True)
diff_merge = diff_merge[diff_merge["_merge"] == "left_only"]

In [53]:
diff_merge.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65 entries, 335 to 1408
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            65 non-null     int64
 1   name          65 non-null     object
 2   position      65 non-null     object
 3   years_active  65 non-null     object
 4   matches       65 non-null     object
 5   norm_name     65 non-null     object
 6   lastname      65 non-null     object
 7   wikidata_id   3 non-null      object
 8   _merge        65 non-null     category
dtypes: category(1), int64(1), object(7)
memory usage: 4.8+ KB

In [54]:
diff_merge

,id,name,position,years_active,matches,norm_name,lastname,wikidata_id,_merge
335,842,John Guidetti,Forward,2022- ?,41,john guidetti,guidetti,Q372276,left_only
1076,1047,Viktor Claesson,,? - ?,1,viktor claesson,claesson,NaN,left_only
1126,364,Carl-Ottil Johansson,Högerback,? -1947,1,carl ottil johansson,johansson,NaN,left_only
1145,1060,David Simbo,,? - ?,,david simbo,simbo,NaN,left_only
1147,1068,John Junior,,? - ?,,john junior,junior,NaN,left_only
...,...,...,...,...,...,...,...,...,...
1392,945,Mohamed Kamara,,? - ?,,mohamed kamara,kamara,NaN,left_only
1395,961,Magnus Bahne,,? - ?,,magnus bahne,bahne,NaN,left_only
1396,970,Joel Enarsson,,? - ?,,joel enarsson,enarsson,NaN,left_only
1400,986,Gzim Istrefi,,? - ?,,gzim istrefi,istrefi,NaN,left_only
1408,831,Omar Jawo,Back,? - ?,,omar jawo,jawo,NaN,left_only

In [59]:
df_table = diff_merge[["id", "name"]].copy()

df_table["url"] = "https://www.aikstats.se/player.php?id=" + df_table["id"].astype(str)

df_table.head(100)

        id                  name                                         url
335    842         John Guidetti   https://www.aikstats.se/player.php?id=842
1076  1047       Viktor Claesson  https://www.aikstats.se/player.php?id=1047
1126   364  Carl-Ottil Johansson   https://www.aikstats.se/player.php?id=364
1145  1060           David Simbo  https://www.aikstats.se/player.php?id=1060
1147  1068           John Junior  https://www.aikstats.se/player.php?id=1068
...    ...                   ...                                         ...
1392   945        Mohamed Kamara   https://www.aikstats.se/player.php?id=945
1395   961          Magnus Bahne   https://www.aikstats.se/player.php?id=961
1396   970         Joel Enarsson   https://www.aikstats.se/player.php?id=970
1400   986          Gzim Istrefi   https://www.aikstats.se/player.php?id=986
1408   831             Omar Jawo   https://www.aikstats.se/player.php?id=831

[65 rows x 3 columns]

In [60]:
df_md = df_table.copy()

df_md["url"] = df_md["id"].apply(
    lambda x: f"[länk](https://www.aikstats.se/player.php?id={x})"
)

md_table = df_md.head(100).to_markdown(index=False)

print(md_table)

|   id | name                   | url                                                |
|-----:|:-----------------------|:---------------------------------------------------|
|  842 | John Guidetti          | [länk](https://www.aikstats.se/player.php?id=842)  |
| 1047 | Viktor Claesson        | [länk](https://www.aikstats.se/player.php?id=1047) |
|  364 | Carl-Ottil Johansson   | [länk](https://www.aikstats.se/player.php?id=364)  |
| 1060 | David Simbo            | [länk](https://www.aikstats.se/player.php?id=1060) |
| 1068 | John Junior            | [länk](https://www.aikstats.se/player.php?id=1068) |
|  797 | Pontus Farnerud        | [länk](https://www.aikstats.se/player.php?id=797)  |
|  922 | Sebastian Hansen       | [länk](https://www.aikstats.se/player.php?id=922)  |
|  932 | Elis Juhlin            | [länk](https://www.aikstats.se/player.php?id=932)  |
|  941 | Hannes Sigurdsson      | [länk](https://www.aikstats.se/player.php?id=941)  |
|  950 | Alagie Sosseh          | [länk](https://www.aikstats.se/player.php?id=950)  |
|  958 | Paulinho Guará         | [länk](https://www.aikstats.se/player.php?id=958)  |
| 1017 | Haisem Ismail          | [länk](https://www.aikstats.se/player.php?id=1017) |
|  833 | Lars "Lasse" Granqvist | [länk](https://www.aikstats.se/player.php?id=833)  |
| 1046 | Aljaz Struna           | [länk](https://www.aikstats.se/player.php?id=1046) |
|  903 | Joel Perovuo           | [länk](https://www.aikstats.se/player.php?id=903)  |
| 1074 | Philip Aremu           | [länk](https://www.aikstats.se/player.php?id=1074) |
| 1108 | Uchenna Ike            | [länk](https://www.aikstats.se/player.php?id=1108) |
|  955 | Petter Hansson         | [länk](https://www.aikstats.se/player.php?id=955)  |
|  963 | Henrik Rydström        | [länk](https://www.aikstats.se/player.php?id=963)  |
|  817 | David Wilson           | [länk](https://www.aikstats.se/player.php?id=817)  |
| 1071 | Mohamed Bangura        | [länk](https://www.aikstats.se/player.php?id=1071) |
| 1071 | Mohamed Bangura        | [länk](https://www.aikstats.se/player.php?id=1071) |
|  924 | Jerry Bengtson         | [länk](https://www.aikstats.se/player.php?id=924)  |
| 1105 | Anthony Allison        | [länk](https://www.aikstats.se/player.php?id=1105) |
| 1163 | Simon Nurme            | [länk](https://www.aikstats.se/player.php?id=1163) |
|  960 | Wanderson do Carmo     | [länk](https://www.aikstats.se/player.php?id=960)  |
|  969 | Erik Sundin            | [länk](https://www.aikstats.se/player.php?id=969)  |
|  985 | Filip Tronêt           | [länk](https://www.aikstats.se/player.php?id=985)  |
| 1003 | William Amamoo         | [länk](https://www.aikstats.se/player.php?id=1003) |
|  814 | Eddie Gustafsson       | [länk](https://www.aikstats.se/player.php?id=814)  |
| 1058 | Norlla Amiri           | [länk](https://www.aikstats.se/player.php?id=1058) |
| 1067 | Branimir Hrgota        | [länk](https://www.aikstats.se/player.php?id=1067) |
|  905 | Philip Haglund         | [länk](https://www.aikstats.se/player.php?id=905)  |
|  921 | Jael Ferreira          | [länk](https://www.aikstats.se/player.php?id=921)  |
| 1093 | Mikael Ishak           | [länk](https://www.aikstats.se/player.php?id=1093) |
|  930 | O Wallentin            | [länk](https://www.aikstats.se/player.php?id=930)  |
|  957 | Tom Wiking             | [länk](https://www.aikstats.se/player.php?id=957)  |
|  810 | Tobias Eriksson        | [länk](https://www.aikstats.se/player.php?id=810)  |
|  827 | Alexander "Alex" Axén  | [länk](https://www.aikstats.se/player.php?id=827)  |
|  832 | Christer Youssef       | [länk](https://www.aikstats.se/player.php?id=832)  |
|  893 | Markus Ekenberg        | [länk](https://www.aikstats.se/player.php?id=893)  |
|  918 | Espen Johnsen          | [länk](https://www.aikstats.se/player.php?id=918)  |
| 1107 | Labinot Harbuzi        | [länk](https://www.aikstats.se/player.php?id=1107) |
| 1117 | Simon Leonidsson       | [länk](https://www.aikstats.se/player.php?id=1117) |
|  962 | Jesper Westerberg      | [länk](https://www.aikstats.se/player.php?id=962)  |
|  816 | Daniel Nannskog        | [länk](https://www.aikstats.se/player.php?id=816)  |
|  854 | Mikael Gustavsson      | [länk](https://www.aikstats.se/player.php?id=854)  |
| 1061 | Patrick Osiako         | [länk](https://www.aikstats.se/player.php?id=1061) |
|  898 | Gustav Jansson         | [länk](https://www.aikstats.se/player.php?id=898)  |
|  933 | Jesper Christiansen    | [länk](https://www.aikstats.se/player.php?id=933)  |
|  959 | Laurent Manuel         | [länk](https://www.aikstats.se/player.php?id=959)  |
|  967 | Filip Burkhardt        | [länk](https://www.aikstats.se/player.php?id=967)  |
|  812 | Nordin Gerzić          | [länk](https://www.aikstats.se/player.php?id=812)  |
| 1018 | Sunday Bale            | [länk](https://www.aikstats.se/player.php?id=1018) |
|  835 | Yussif Chibsah         | [länk](https://www.aikstats.se/player.php?id=835)  |
| 1101 | David Accam            | [länk](https://www.aikstats.se/player.php?id=1101) |
|  964 | Jamal Mohammed         | [länk](https://www.aikstats.se/player.php?id=964)  |
|  826 | Labinot Kelmendi       | [länk](https://www.aikstats.se/player.php?id=826)  |
| 1080 | Mohammed Saied         | [länk](https://www.aikstats.se/player.php?id=1080) |
| 1106 | Dijan Vukojević        | [länk](https://www.aikstats.se/player.php?id=1106) |
|  945 | Mohamed Kamara         | [länk](https://www.aikstats.se/player.php?id=945)  |
|  961 | Magnus Bahne           | [länk](https://www.aikstats.se/player.php?id=961)  |
|  970 | Joel Enarsson          | [länk](https://www.aikstats.se/player.php?id=970)  |
|  986 | Gzim Istrefi           | [länk](https://www.aikstats.se/player.php?id=986)  |
|  831 | Omar Jawo              | [länk](https://www.aikstats.se/player.php?id=831)  |