* [#41](https://github.com/salgo60/ifkdb/issues/41)
* denna Notebook [41_fotbolltransfers.ipynb](https://github.com/salgo60/ifkdb/blob/main/Notebook/41_fotbolltransfers.ipynb)

* Mixandmatch [catalog/7732](https://mix-n-match.toolforge.org/#/catalog/7732)

In [1]:
import sys
print(sys.executable)

/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12

In [2]:
#!pip3 install aiohttp

In [3]:
import time

from datetime import datetime

now = datetime.now()
timestamp = now.timestamp()

start_time = time.time()
print("Start:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Start: 2026-03-20 14:09:58

In [41]:
import requests
from bs4 import BeautifulSoup
import time
from tqdm import tqdm
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
import json
import os
import re

BASE_PLAYER_URL = "https://fotbolltransfers.com/spelare/x/{}"

SAVE_FILE = "resultsPlayer_partial.json"
FINAL_FILE = "resultsPlayer.json"

headers = {
    "User-Agent": "Mozilla/5.0 (compatible; Wikidatascraper/1.0 salgo60@msn.com)"
}

session = requests.Session()

retries = Retry(
    total=5,
    backoff_factor=0.5,
    status_forcelist=[429, 500, 502, 503, 504],
)

adapter = HTTPAdapter(max_retries=retries)
session.mount("https://", adapter)
session.mount("http://", adapter)

# resume
if os.path.exists(SAVE_FILE):
    with open(SAVE_FILE, "r", encoding="utf-8") as f:
        resultsPlayer = json.load(f)
    print(f"Återupptar från {len(resultsPlayer)} spelare")
else:
    resultsPlayer = []

existing_ids = {item["numeric_id"] for item in resultsPlayer}
start_id = max(existing_ids) + 1 if existing_ids else 1

print(f"Startar från player_id = {start_id}")

SAVE_EVERY = 100
MAX_EMPTY_STREAK = 200
empty_streak = 0


def slugify(text):
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = text.replace(" ", "-")
    return text


def clean_text(text):
    if not text:
        return None
    return re.sub(r"\s+", " ", text).strip()


def extract_profile_fields(soup):
    """
    Hämtar spelardata från tabellen med etikett i första <td>
    och värde i andra <td>.
    """
    wanted = {
        "Födelsedatum": "birth_date",
        "Längd": "height",
        "Vikt": "weight",
        "Position": "position",
        "Moderklubb": "youth_club",
        "Nationalitet": "nationality",
    }

    data = {v: None for v in wanted.values()}

    for row in soup.select("tbody tr"):
        cols = row.find_all("td")
        if len(cols) < 2:
            continue

        label = clean_text(cols[0].get_text(" ", strip=True))
        value = clean_text(cols[1].get_text(" ", strip=True))

        if not label:
            continue

        label = label.rstrip(":").strip()

        if label in wanted:
            data[wanted[label]] = value

    return data


#for player_id in tqdm(range(start_id, 15500)):
for player_id in tqdm(range(start_id, 200)):
    url = BASE_PLAYER_URL.format(player_id)

    try:
        r = session.get(url, headers=headers, timeout=10)

        if r.status_code != 200:
            empty_streak += 1
            continue

        soup = BeautifulSoup(r.text, "html.parser")

        if not soup.title or not soup.title.string:
            empty_streak += 1
            continue

        name = soup.title.string.split(" - ")[0].strip()

        if name == "Fotbolltransfers.com":
            empty_streak += 1
            continue

        slug = slugify(name)
        full_id = f"spelare/{slug}/{player_id}"
        full_url = f"https://fotbolltransfers.com/{full_id}"

        profile_data = extract_profile_fields(soup)

        resultsPlayer.append({
            "id": full_id,
            "name": name,
            "url": full_url,
            "numeric_id": player_id,
            "birth_date": profile_data["birth_date"],
            "height": profile_data["height"],
            "weight": profile_data["weight"],
            "position": profile_data["position"],
            "youth_club": profile_data["youth_club"],
            "nationality": profile_data["nationality"],
        })

        empty_streak = 0

    except requests.exceptions.RequestException as e:
        print(f"Error {player_id}: {e}")
        empty_streak += 1
        continue

    if player_id % SAVE_EVERY == 0:
        with open(SAVE_FILE, "w", encoding="utf-8") as f:
            json.dump(resultsPlayer, f, ensure_ascii=False)

    if empty_streak >= MAX_EMPTY_STREAK:
        print(f"\n🛑 Stoppar: {empty_streak} tomma i rad vid ID {player_id}")
        break

    time.sleep(0.2)

with open(FINAL_FILE, "w", encoding="utf-8") as f:
    json.dump(resultsPlayer, f, ensure_ascii=False, indent=2)

print(f"Klar! Spelare funna: {len(resultsPlayer)}")

Startar från player_id = 1

 31%|█████████████                             | 62/199 [01:26<19:48,  8.68s/it]

Error 62: HTTPSConnectionPool(host='fotbolltransfers.com', port=443): Max retries exceeded with url: /spelare/x/62 (Caused by ResponseError('too many 500 error responses'))

100%|█████████████████████████████████████████| 199/199 [03:50<00:00,  1.16s/it]

Klar! Spelare funna: 152

In [39]:
resultsPlayer

[{'id': 'spelare/kim-christensen/37',
  'name': 'Kim Christensen',
  'url': 'https://fotbolltransfers.com/spelare/kim-christensen/37',
  'numeric_id': 37},
 {'id': 'spelare/marcus-sandberg/38',
  'name': 'Marcus Sandberg',
  'url': 'https://fotbolltransfers.com/spelare/marcus-sandberg/38',
  'numeric_id': 38},
 {'id': 'spelare/karl-svensson/39',
  'name': 'Karl Svensson',
  'url': 'https://fotbolltransfers.com/spelare/karl-svensson/39',
  'numeric_id': 39},
 {'id': 'spelare/nicklas-carlsson/40',
  'name': 'Nicklas Carlsson',
  'url': 'https://fotbolltransfers.com/spelare/nicklas-carlsson/40',
  'numeric_id': 40},
 {'id': 'spelare/petter-björlund/41',
  'name': 'Petter Björlund',
  'url': 'https://fotbolltransfers.com/spelare/petter-björlund/41',
  'numeric_id': 41},
 {'id': 'spelare/tuomo-turunen/42',
  'name': 'Tuomo Turunen',
  'url': 'https://fotbolltransfers.com/spelare/tuomo-turunen/42',
  'numeric_id': 42},
 {'id': 'spelare/adam-johansson/43',
  'name': 'Adam Johansson',
  'url': 'https://fotbolltransfers.com/spelare/adam-johansson/43',
  'numeric_id': 43},
 {'id': 'spelare/tobias-hysén/45',
  'name': 'Tobias Hysén',
  'url': 'https://fotbolltransfers.com/spelare/tobias-hysén/45',
  'numeric_id': 45},
 {'id': 'spelare/thomas-olsson/46',
  'name': 'Thomas Olsson',
  'url': 'https://fotbolltransfers.com/spelare/thomas-olsson/46',
  'numeric_id': 46},
 {'id': 'spelare/stefan-selakovic/47',
  'name': 'Stefan Selakovic',
  'url': 'https://fotbolltransfers.com/spelare/stefan-selakovic/47',
  'numeric_id': 47},
 {'id': 'spelare/ragnar-sigurdsson/48',
  'name': 'Ragnar Sigurdsson',
  'url': 'https://fotbolltransfers.com/spelare/ragnar-sigurdsson/48',
  'numeric_id': 48},
 {'id': 'spelare/robin-söder/49',
  'name': 'Robin Söder',
  'url': 'https://fotbolltransfers.com/spelare/robin-söder/49',
  'numeric_id': 49},
 {'id': 'spelare/gustav-svensson/50',
  'name': 'Gustav Svensson',
  'url': 'https://fotbolltransfers.com/spelare/gustav-svensson/50',
  'numeric_id': 50},
 {'id': 'spelare/hjálmar-jónsson/51',
  'name': 'Hjálmar Jónsson',
  'url': 'https://fotbolltransfers.com/spelare/hjálmar-jónsson/51',
  'numeric_id': 51},
 {'id': 'spelare/jakob-johansson/52',
  'name': 'Jakob Johansson',
  'url': 'https://fotbolltransfers.com/spelare/jakob-johansson/52',
  'numeric_id': 52},
 {'id': 'spelare/tomi-maanoja/53',
  'name': 'Tomi Maanoja',
  'url': 'https://fotbolltransfers.com/spelare/tomi-maanoja/53',
  'numeric_id': 53},
 {'id': 'spelare/erik-lund/54',
  'name': 'Erik Lund',
  'url': 'https://fotbolltransfers.com/spelare/erik-lund/54',
  'numeric_id': 54},
 {'id': 'spelare/nicklas-bergh/55',
  'name': 'Nicklas Bergh',
  'url': 'https://fotbolltransfers.com/spelare/nicklas-bergh/55',
  'numeric_id': 55},
 {'id': 'spelare/daniel-alexandersson/56',
  'name': 'Daniel Alexandersson',
  'url': 'https://fotbolltransfers.com/spelare/daniel-alexandersson/56',
  'numeric_id': 56},
 {'id': 'spelare/patrik-bojent/57',
  'name': 'Patrik Bojent',
  'url': 'https://fotbolltransfers.com/spelare/patrik-bojent/57',
  'numeric_id': 57},
 {'id': 'spelare/nicklas-bärkroth/58',
  'name': 'Nicklas Bärkroth',
  'url': 'https://fotbolltransfers.com/spelare/nicklas-bärkroth/58',
  'numeric_id': 58},
 {'id': 'spelare/tobias-sana/59',
  'name': 'Tobias Sana',
  'url': 'https://fotbolltransfers.com/spelare/tobias-sana/59',
  'numeric_id': 59},
 {'id': 'spelare/sebastian-eriksson/60',
  'name': 'Sebastian Eriksson',
  'url': 'https://fotbolltransfers.com/spelare/sebastian-eriksson/60',
  'numeric_id': 60},
 {'id': 'spelare/mikael-dyrestam/61',
  'name': 'Mikael Dyrestam',
  'url': 'https://fotbolltransfers.com/spelare/mikael-dyrestam/61',
  'numeric_id': 61},
 {'id': 'spelare/elmar-bjarnason/62',
  'name': 'Elmar Bjarnason',
  'url': 'https://fotbolltransfers.com/spelare/elmar-bjarnason/62',
  'numeric_id': 62},
 {'id': 'spelare/kamal-mustafa/64',
  'name': 'Kamal Mustafa',
  'url': 'https://fotbolltransfers.com/spelare/kamal-mustafa/64',
  'numeric_id': 64},
 {'id': 'spelare/hannes-stiller/65',
  'name': 'Hannes Stiller',
  'url': 'https://fotbolltransfers.com/spelare/hannes-stiller/65',
  'numeric_id': 65},
 {'id': 'spelare/per-karlsson/66',
  'name': 'Per Karlsson',
  'url': 'https://fotbolltransfers.com/spelare/per-karlsson/66',
  'numeric_id': 66},
 {'id': 'spelare/nils-eric-johansson/67',
  'name': 'Nils-Eric Johansson',
  'url': 'https://fotbolltransfers.com/spelare/nils-eric-johansson/67',
  'numeric_id': 67},
 {'id': 'spelare/jorge-ortiz/68',
  'name': 'Jorge Ortiz',
  'url': 'https://fotbolltransfers.com/spelare/jorge-ortiz/68',
  'numeric_id': 68},
 {'id': 'spelare/johan-lundgren/69',
  'name': 'Johan Lundgren',
  'url': 'https://fotbolltransfers.com/spelare/johan-lundgren/69',
  'numeric_id': 69},
 {'id': 'spelare/walid-atta/70',
  'name': 'Walid Atta',
  'url': 'https://fotbolltransfers.com/spelare/walid-atta/70',
  'numeric_id': 70},
 {'id': 'spelare/erik-dahlin/71',
  'name': 'Erik Dahlin',
  'url': 'https://fotbolltransfers.com/spelare/erik-dahlin/71',
  'numeric_id': 71},
 {'id': 'spelare/bojan-djordjic/72',
  'name': 'Bojan Djordjic',
  'url': 'https://fotbolltransfers.com/spelare/bojan-djordjic/72',
  'numeric_id': 72},
 {'id': 'spelare/daniel-tjernström/73',
  'name': 'Daniel Tjernström',
  'url': 'https://fotbolltransfers.com/spelare/daniel-tjernström/73',
  'numeric_id': 73},
 {'id': 'spelare/miran-burgic/74',
  'name': 'Miran Burgic',
  'url': 'https://fotbolltransfers.com/spelare/miran-burgic/74',
  'numeric_id': 74},
 {'id': 'spelare/iván-obolo/75',
  'name': 'Iván Obolo',
  'url': 'https://fotbolltransfers.com/spelare/iván-obolo/75',
  'numeric_id': 75},
 {'id': 'spelare/kenny-pavey/76',
  'name': 'Kenny Pavey',
  'url': 'https://fotbolltransfers.com/spelare/kenny-pavey/76',
  'numeric_id': 76},
 {'id': 'spelare/kevin-walker/77',
  'name': 'Kevin Walker',
  'url': 'https://fotbolltransfers.com/spelare/kevin-walker/77',
  'numeric_id': 77},
 {'id': 'spelare/saihou-jagne/79',
  'name': 'Saihou Jagne',
  'url': 'https://fotbolltransfers.com/spelare/saihou-jagne/79',
  'numeric_id': 79},
 {'id': 'spelare/markus-jonsson/80',
  'name': 'Markus Jonsson',
  'url': 'https://fotbolltransfers.com/spelare/markus-jonsson/80',
  'numeric_id': 80},
 {'id': 'spelare/martin-mutumba/81',
  'name': 'Martin Mutumba',
  'url': 'https://fotbolltransfers.com/spelare/martin-mutumba/81',
  'numeric_id': 81},
 {'id': 'spelare/jos-hooiveld/82',
  'name': 'Jos Hooiveld',
  'url': 'https://fotbolltransfers.com/spelare/jos-hooiveld/82',
  'numeric_id': 82},
 {'id': 'spelare/mikael-thorstensson/83',
  'name': 'Mikael Thorstensson',
  'url': 'https://fotbolltransfers.com/spelare/mikael-thorstensson/83',
  'numeric_id': 83},
 {'id': 'spelare/yussuf-saleh/84',
  'name': 'Yussuf Saleh',
  'url': 'https://fotbolltransfers.com/spelare/yussuf-saleh/84',
  'numeric_id': 84},
 {'id': 'spelare/pontus-engblom/85',
  'name': 'Pontus Engblom',
  'url': 'https://fotbolltransfers.com/spelare/pontus-engblom/85',
  'numeric_id': 85},
 {'id': 'spelare/viktor-lundberg/86',
  'name': 'Viktor Lundberg',
  'url': 'https://fotbolltransfers.com/spelare/viktor-lundberg/86',
  'numeric_id': 86},
 {'id': 'spelare/gabriel-özkan/87',
  'name': 'Gabriel Özkan',
  'url': 'https://fotbolltransfers.com/spelare/gabriel-özkan/87',
  'numeric_id': 87},
 {'id': 'spelare/dulee-johnson/88',
  'name': 'Dulee Johnson',
  'url': 'https://fotbolltransfers.com/spelare/dulee-johnson/88',
  'numeric_id': 88},
 {'id': 'spelare/lee-baxter/89',
  'name': 'Lee Baxter',
  'url': 'https://fotbolltransfers.com/spelare/lee-baxter/89',
  'numeric_id': 89},
 {'id': 'spelare/antonio-flavio/90',
  'name': 'Antonio Flavio',
  'url': 'https://fotbolltransfers.com/spelare/antonio-flavio/90',
  'numeric_id': 90},
 {'id': 'spelare/niklas-backman/91',
  'name': 'Niklas Backman',
  'url': 'https://fotbolltransfers.com/spelare/niklas-backman/91',
  'numeric_id': 91},
 {'id': 'spelare/joakim-wulff/92',
  'name': 'Joakim Wulff',
  'url': 'https://fotbolltransfers.com/spelare/joakim-wulff/92',
  'numeric_id': 92},
 {'id': 'spelare/ante-covic/93',
  'name': 'Ante Covic',
  'url': 'https://fotbolltransfers.com/spelare/ante-covic/93',
  'numeric_id': 93},
 {'id': 'spelare/mathias-florén/95',
  'name': 'Mathias Florén',
  'url': 'https://fotbolltransfers.com/spelare/mathias-florén/95',
  'numeric_id': 95},
 {'id': 'spelare/johan-karlsson/96',
  'name': 'Johan Karlsson',
  'url': 'https://fotbolltransfers.com/spelare/johan-karlsson/96',
  'numeric_id': 96},
 {'id': 'spelare/martin-andersson/97',
  'name': 'Martin Andersson',
  'url': 'https://fotbolltransfers.com/spelare/martin-andersson/97',
  'numeric_id': 97},
 {'id': 'spelare/helgi-danielsson/98',
  'name': 'Helgi Danielsson',
  'url': 'https://fotbolltransfers.com/spelare/helgi-danielsson/98',
  'numeric_id': 98},
 {'id': 'spelare/jari-ilola/99',
  'name': 'Jari Ilola',
  'url': 'https://fotbolltransfers.com/spelare/jari-ilola/99',
  'numeric_id': 99},
 {'id': 'spelare/pa-dembo-touray/100',
  'name': 'Pa Dembo Touray',
  'url': 'https://fotbolltransfers.com/spelare/pa-dembo-touray/100',
  'numeric_id': 100},
 {'id': 'spelare/anders-svensson/101',
  'name': 'Anders Svensson',
  'url': 'https://fotbolltransfers.com/spelare/anders-svensson/101',
  'numeric_id': 101},
 {'id': 'spelare/denni-avdic/102',
  'name': 'Denni Avdic',
  'url': 'https://fotbolltransfers.com/spelare/denni-avdic/102',
  'numeric_id': 102},
 {'id': 'spelare/oskar-wahlström/103',
  'name': 'Oskar Wahlström',
  'url': 'https://fotbolltransfers.com/spelare/oskar-wahlström/103',
  'numeric_id': 103},
 {'id': 'spelare/tommi-vaiho/104',
  'name': 'Tommi Vaiho',
  'url': 'https://fotbolltransfers.com/spelare/tommi-vaiho/104',
  'numeric_id': 104},
 {'id': 'spelare/martin-ericsson/105',
  'name': 'Martin Ericsson',
  'url': 'https://fotbolltransfers.com/spelare/martin-ericsson/105',
  'numeric_id': 105},
 {'id': 'spelare/philip-hellqvist/106',
  'name': 'Philip Hellqvist',
  'url': 'https://fotbolltransfers.com/spelare/philip-hellqvist/106',
  'numeric_id': 106},
 {'id': 'spelare/daniel-mobaeck/107',
  'name': 'Daniel Mobaeck',
  'url': 'https://fotbolltransfers.com/spelare/daniel-mobaeck/107',
  'numeric_id': 107},
 {'id': 'spelare/amadou-jawo/108',
  'name': 'Amadou Jawo',
  'url': 'https://fotbolltransfers.com/spelare/amadou-jawo/108',
  'numeric_id': 108},
 {'id': 'spelare/anders-wikström/109',
  'name': 'Anders Wikström',
  'url': 'https://fotbolltransfers.com/spelare/anders-wikström/109',
  'numeric_id': 109},
 {'id': 'spelare/yosif-ayuba/110',
  'name': 'Yosif Ayuba',
  'url': 'https://fotbolltransfers.com/spelare/yosif-ayuba/110',
  'numeric_id': 110},
 {'id': 'spelare/jesper-florén/111',
  'name': 'Jesper Florén',
  'url': 'https://fotbolltransfers.com/spelare/jesper-florén/111',
  'numeric_id': 111},
 {'id': 'spelare/patrik-haginge/112',
  'name': 'Patrik Haginge',
  'url': 'https://fotbolltransfers.com/spelare/patrik-haginge/112',
  'numeric_id': 112},
 {'id': 'spelare/teddy-lucic/113',
  'name': 'Teddy Lucic',
  'url': 'https://fotbolltransfers.com/spelare/teddy-lucic/113',
  'numeric_id': 113},
 {'id': 'spelare/daniel-nordmark/114',
  'name': 'Daniel Nordmark',
  'url': 'https://fotbolltransfers.com/spelare/daniel-nordmark/114',
  'numeric_id': 114},
 {'id': 'spelare/petter-gustafsson/115',
  'name': 'Petter Gustafsson',
  'url': 'https://fotbolltransfers.com/spelare/petter-gustafsson/115',
  'numeric_id': 115},
 {'id': 'spelare/james-keene/116',
  'name': 'James Keene',
  'url': 'https://fotbolltransfers.com/spelare/james-keene/116',
  'numeric_id': 116},
 {'id': 'spelare/briar-faraj/117',
  'name': 'Briar Faraj',
  'url': 'https://fotbolltransfers.com/spelare/briar-faraj/117',
  'numeric_id': 117},
 {'id': 'spelare/joel-anell/118',
  'name': 'Joel Anell',
  'url': 'https://fotbolltransfers.com/spelare/joel-anell/118',
  'numeric_id': 118},
 {'id': 'spelare/emir-bajrami/119',
  'name': 'Emir Bajrami',
  'url': 'https://fotbolltransfers.com/spelare/emir-bajrami/119',
  'numeric_id': 119},
 {'id': 'spelare/henrik-svedberg/120',
  'name': 'Henrik Svedberg',
  'url': 'https://fotbolltransfers.com/spelare/henrik-svedberg/120',
  'numeric_id': 120},
 {'id': 'spelare/toni-kuivasto/121',
  'name': 'Toni Kuivasto',
  'url': 'https://fotbolltransfers.com/spelare/toni-kuivasto/121',
  'numeric_id': 121},
 {'id': 'spelare/niklas-hult/122',
  'name': 'Niklas Hult',
  'url': 'https://fotbolltransfers.com/spelare/niklas-hult/122',
  'numeric_id': 122},
 {'id': 'spelare/stefan-ishizaki/123',
  'name': 'Stefan Ishizaki',
  'url': 'https://fotbolltransfers.com/spelare/stefan-ishizaki/123',
  'numeric_id': 123},
 {'id': 'spelare/elmin-kurbegovic/124',
  'name': 'Elmin Kurbegovic',
  'url': 'https://fotbolltransfers.com/spelare/elmin-kurbegovic/124',
  'numeric_id': 124},
 {'id': 'spelare/prince-ikpe-ekong/125',
  'name': 'Prince Ikpe Ekong',
  'url': 'https://fotbolltransfers.com/spelare/prince-ikpe-ekong/125',
  'numeric_id': 125},
 {'id': 'spelare/andreas-andersson/126',
  'name': 'Andreas Andersson',
  'url': 'https://fotbolltransfers.com/spelare/andreas-andersson/126',
  'numeric_id': 126},
 {'id': 'spelare/johan-sjöberg/127',
  'name': 'Johan Sjöberg',
  'url': 'https://fotbolltransfers.com/spelare/johan-sjöberg/127',
  'numeric_id': 127},
 {'id': 'spelare/fredrik-berglund/128',
  'name': 'Fredrik Berglund',
  'url': 'https://fotbolltransfers.com/spelare/fredrik-berglund/128',
  'numeric_id': 128},
 {'id': 'spelare/jan-tauer/129',
  'name': 'Jan Tauer',
  'url': 'https://fotbolltransfers.com/spelare/jan-tauer/129',
  'numeric_id': 129},
 {'id': 'spelare/johan-oremo/131',
  'name': 'Johan Oremo',
  'url': 'https://fotbolltransfers.com/spelare/johan-oremo/131',
  'numeric_id': 131},
 {'id': 'spelare/christer-youssef/132',
  'name': 'Christer Youssef',
  'url': 'https://fotbolltransfers.com/spelare/christer-youssef/132',
  'numeric_id': 132},
 {'id': 'spelare/daniel-sjölund/133',
  'name': 'Daniel Sjölund',
  'url': 'https://fotbolltransfers.com/spelare/daniel-sjölund/133',
  'numeric_id': 133},
 {'id': 'spelare/mattias-jonson/134',
  'name': 'Mattias Jonson',
  'url': 'https://fotbolltransfers.com/spelare/mattias-jonson/134',
  'numeric_id': 134},
 {'id': 'spelare/kebba-ceesay/135',
  'name': 'Kebba Ceesay',
  'url': 'https://fotbolltransfers.com/spelare/kebba-ceesay/135',
  'numeric_id': 135},
 {'id': 'spelare/rami-shaaban/136',
  'name': 'Rami Shaaban',
  'url': 'https://fotbolltransfers.com/spelare/rami-shaaban/136',
  'numeric_id': 136},
 {'id': 'spelare/markus-johannesson/137',
  'name': 'Markus Johannesson',
  'url': 'https://fotbolltransfers.com/spelare/markus-johannesson/137',
  'numeric_id': 137},
 {'id': 'spelare/boyd-mwila/138',
  'name': 'Boyd Mwila',
  'url': 'https://fotbolltransfers.com/spelare/boyd-mwila/138',
  'numeric_id': 138},
 {'id': 'spelare/mikael-dahlberg/139',
  'name': 'Mikael Dahlberg',
  'url': 'https://fotbolltransfers.com/spelare/mikael-dahlberg/139',
  'numeric_id': 139},
 {'id': 'spelare/hrvoje-milic/140',
  'name': 'Hrvoje Milic',
  'url': 'https://fotbolltransfers.com/spelare/hrvoje-milic/140',
  'numeric_id': 140},
 {'id': 'spelare/martin-andersson/141',
  'name': 'Martin Andersson',
  'url': 'https://fotbolltransfers.com/spelare/martin-andersson/141',
  'numeric_id': 141},
 {'id': 'spelare/peter-magnusson/142',
  'name': 'Peter Magnusson',
  'url': 'https://fotbolltransfers.com/spelare/peter-magnusson/142',
  'numeric_id': 142},
 {'id': 'spelare/sebastian-rajalakso/143',
  'name': 'Sebastian Rajalakso',
  'url': 'https://fotbolltransfers.com/spelare/sebastian-rajalakso/143',
  'numeric_id': 143},
 {'id': 'spelare/max-von-schlebrügge/144',
  'name': 'Max von Schlebrügge',
  'url': 'https://fotbolltransfers.com/spelare/max-von-schlebrügge/144',
  'numeric_id': 144},
 {'id': 'spelare/samuel-holmén/145',
  'name': 'Samuel Holmén',
  'url': 'https://fotbolltransfers.com/spelare/samuel-holmén/145',
  'numeric_id': 145},
 {'id': 'spelare/jon-jönsson/146',
  'name': 'Jon Jönsson',
  'url': 'https://fotbolltransfers.com/spelare/jon-jönsson/146',
  'numeric_id': 146},
 {'id': 'spelare/mikael-nilsson/147',
  'name': 'Mikael Nilsson',
  'url': 'https://fotbolltransfers.com/spelare/mikael-nilsson/147',
  'numeric_id': 147},
 {'id': 'spelare/alexander-farnerud/148',
  'name': 'Alexander Farnerud',
  'url': 'https://fotbolltransfers.com/spelare/alexander-farnerud/148',
  'numeric_id': 148},
 {'id': 'spelare/jani-lyyski/149',
  'name': 'Jani Lyyski',
  'url': 'https://fotbolltransfers.com/spelare/jani-lyyski/149',
  'numeric_id': 149},
 {'id': 'spelare/kennedy-igboananike/150',
  'name': 'Kennedy Igboananike',
  'url': 'https://fotbolltransfers.com/spelare/kennedy-igboananike/150',
  'numeric_id': 150},
 {'id': 'spelare/kristoffer-björklund/152',
  'name': 'Kristoffer Björklund',
  'url': 'https://fotbolltransfers.com/spelare/kristoffer-björklund/152',
  'numeric_id': 152},
 {'id': 'spelare/johannes-hopf/153',
  'name': 'Johannes Hopf',
  'url': 'https://fotbolltransfers.com/spelare/johannes-hopf/153',
  'numeric_id': 153},
 {'id': 'spelare/david-lidholm/154',
  'name': 'David Lidholm',
  'url': 'https://fotbolltransfers.com/spelare/david-lidholm/154',
  'numeric_id': 154},
 {'id': 'spelare/josé-monteiro/155',
  'name': 'José Monteiro',
  'url': 'https://fotbolltransfers.com/spelare/josé-monteiro/155',
  'numeric_id': 155},
 {'id': 'spelare/christian-traoré/156',
  'name': 'Christian Traoré',
  'url': 'https://fotbolltransfers.com/spelare/christian-traoré/156',
  'numeric_id': 156},
 {'id': 'spelare/emil-johansson/157',
  'name': 'Emil Johansson',
  'url': 'https://fotbolltransfers.com/spelare/emil-johansson/157',
  'numeric_id': 157},
 {'id': 'spelare/patrik-gerrbrand/158',
  'name': 'Patrik Gerrbrand',
  'url': 'https://fotbolltransfers.com/spelare/patrik-gerrbrand/158',
  'numeric_id': 158},
 {'id': 'spelare/carlos-gaete-moggia/159',
  'name': 'Carlos Gaete Moggia',
  'url': 'https://fotbolltransfers.com/spelare/carlos-gaete-moggia/159',
  'numeric_id': 159},
 {'id': 'spelare/fredrik-söderström/160',
  'name': 'Fredrik Söderström',
  'url': 'https://fotbolltransfers.com/spelare/fredrik-söderström/160',
  'numeric_id': 160},
 {'id': 'spelare/sebastian-castro-tello/161',
  'name': 'Sebastian Castro-Tello',
  'url': 'https://fotbolltransfers.com/spelare/sebastian-castro-tello/161',
  'numeric_id': 161},
 {'id': 'spelare/freddy-söderberg/162',
  'name': 'Freddy Söderberg',
  'url': 'https://fotbolltransfers.com/spelare/freddy-söderberg/162',
  'numeric_id': 162},
 {'id': 'spelare/igor-armas/163',
  'name': 'Igor Armas',
  'url': 'https://fotbolltransfers.com/spelare/igor-armas/163',
  'numeric_id': 163},
 {'id': 'spelare/nathan-paulse/166',
  'name': 'Nathan Paulse',
  'url': 'https://fotbolltransfers.com/spelare/nathan-paulse/166',
  'numeric_id': 166},
 {'id': 'spelare/christer-gustafsson/167',
  'name': 'Christer Gustafsson',
  'url': 'https://fotbolltransfers.com/spelare/christer-gustafsson/167',
  'numeric_id': 167},
 {'id': 'spelare/linus-hallenius/169',
  'name': 'Linus Hallenius',
  'url': 'https://fotbolltransfers.com/spelare/linus-hallenius/169',
  'numeric_id': 169},
 {'id': 'spelare/haris-laitinen/170',
  'name': 'Haris Laitinen',
  'url': 'https://fotbolltransfers.com/spelare/haris-laitinen/170',
  'numeric_id': 170},
 {'id': 'spelare/andreas-dahl/171',
  'name': 'Andreas Dahl',
  'url': 'https://fotbolltransfers.com/spelare/andreas-dahl/171',
  'numeric_id': 171},
 {'id': 'spelare/maic-sema/172',
  'name': 'Maic Sema',
  'url': 'https://fotbolltransfers.com/spelare/maic-sema/172',
  'numeric_id': 172},
 {'id': 'spelare/simon-helg/173',
  'name': 'Simon Helg',
  'url': 'https://fotbolltransfers.com/spelare/simon-helg/173',
  'numeric_id': 173},
 {'id': 'spelare/vlado-zlojutro/174',
  'name': 'Vlado Zlojutro',
  'url': 'https://fotbolltransfers.com/spelare/vlado-zlojutro/174',
  'numeric_id': 174},
 {'id': 'spelare/marcus-törnstrand/175',
  'name': 'Marcus Törnstrand',

In [5]:
import re

BASE_TEAM_URL = "https://fotbolltransfers.com/klubbar/x/xx/{}"

SAVE_FILE = "resultsTeam_partial.json"
FINAL_FILE = "resultsTeam.json"

# 🔄 resume
if os.path.exists(SAVE_FILE):
    with open(SAVE_FILE, "r", encoding="utf-8") as f:
        resultsTeam = json.load(f)
else:
    resultsTeam = []

existing_ids = {item["numeric_id"] for item in resultsTeam}
start_id = max(existing_ids) + 1 if existing_ids else 1

def slugify(text):
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = text.replace(" ", "-")
    return text

for team_id in tqdm(range(start_id, 6800)):
    url = BASE_TEAM_URL.format(team_id)

    try:
        r = session.get(url, headers=headers, timeout=10)

        if r.status_code != 200:
            empty_streak += 1
            continue

        soup = BeautifulSoup(r.text, "html.parser")

        if not soup.title or not soup.title.string:
            empty_streak += 1
            continue

        name = soup.title.string.split(" - ")[0].strip()

        if name == "Fotbolltransfers.com":
            empty_streak += 1
            continue

        link = soup.find("link", rel="canonical")
        full_url = link["href"]
        full_id = full_url.replace("https://fotbolltransfers.com/", "")

        slug = slugify(name)

        resultsTeam.append({
            "id": full_id,
            "name": name,
            "url": full_url,
            "numeric_id": team_id
        })

        empty_streak = 0

    except requests.exceptions.RequestException:
        empty_streak += 1
        continue

    if team_id % SAVE_EVERY == 0:
        with open(SAVE_FILE, "w", encoding="utf-8") as f:
            json.dump(resultsTeam, f, ensure_ascii=False)

    if empty_streak >= MAX_EMPTY_STREAK:
        break

    time.sleep(0.1)

with open(FINAL_FILE, "w", encoding="utf-8") as f:
    json.dump(resultsTeam, f, ensure_ascii=False, indent=2)

100%|█████████████████████████████████████| 6799/6799 [1:44:07<00:00,  1.09it/s]

In [6]:
import json

with open("resultsTeam_snapshot.json", "w", encoding="utf-8") as f:
    json.dump(resultsTeam, f, ensure_ascii=False, indent=2)

print("Snapshot sparad ✅")

Snapshot sparad ✅

In [25]:
#resultsPlayer

In [7]:
import pandas as pd

In [28]:
dfPlayers = pd.DataFrame(resultsPlayer,columns=['id','name','url','numeric_id'])

In [29]:
dfPlayers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14090 entries, 0 to 14089
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          14090 non-null  object
 1   name        14090 non-null  object
 2   url         14090 non-null  object
 3   numeric_id  14090 non-null  int64
dtypes: int64(1), object(3)
memory usage: 440.4+ KB

In [30]:
dfPlayers.head(10)

,id,name,url,numeric_id
0,spelare/kim-christensen/37,Kim Christensen,https://fotbolltransfers.com/spelare/kim-chris...,37
1,spelare/marcus-sandberg/38,Marcus Sandberg,https://fotbolltransfers.com/spelare/marcus-sa...,38
2,spelare/karl-svensson/39,Karl Svensson,https://fotbolltransfers.com/spelare/karl-sven...,39
3,spelare/nicklas-carlsson/40,Nicklas Carlsson,https://fotbolltransfers.com/spelare/nicklas-c...,40
4,spelare/petter-björlund/41,Petter Björlund,https://fotbolltransfers.com/spelare/petter-bj...,41
5,spelare/tuomo-turunen/42,Tuomo Turunen,https://fotbolltransfers.com/spelare/tuomo-tur...,42
6,spelare/adam-johansson/43,Adam Johansson,https://fotbolltransfers.com/spelare/adam-joha...,43
7,spelare/tobias-hysén/45,Tobias Hysén,https://fotbolltransfers.com/spelare/tobias-hy...,45
8,spelare/thomas-olsson/46,Thomas Olsson,https://fotbolltransfers.com/spelare/thomas-ol...,46
9,spelare/stefan-selakovic/47,Stefan Selakovic,https://fotbolltransfers.com/spelare/stefan-se...,47

In [31]:
dfPlayer.tail(10)

,id,name,url,numeric_id
14080,spelare/elton-levin/15105,Elton Levin,https://fotbolltransfers.com/spelare/elton-lev...,15105
14081,spelare/oliver-klang/15106,Oliver Klang,https://fotbolltransfers.com/spelare/oliver-kl...,15106
14082,spelare/oliver-schaaf/15107,Oliver Schaaf,https://fotbolltransfers.com/spelare/oliver-sc...,15107
14083,spelare/vilmer-johansson/15108,Vilmer Johansson,https://fotbolltransfers.com/spelare/vilmer-jo...,15108
14084,spelare/mario-palomino-delgado/15109,Mario Palomino Delgado,https://fotbolltransfers.com/spelare/mario-pal...,15109
14085,spelare/sindri-kristinn-ólafsson/15110,Sindri Kristinn Ólafsson,https://fotbolltransfers.com/spelare/sindri-kr...,15110
14086,spelare/elion-lipovica/15111,Elion Lipovica,https://fotbolltransfers.com/spelare/elion-lip...,15111
14087,spelare/ebbe-orrling/15112,Ebbe Orrling,https://fotbolltransfers.com/spelare/ebbe-orrl...,15112
14088,spelare/hannes-nyman/15113,Hannes Nyman,https://fotbolltransfers.com/spelare/hannes-ny...,15113
14089,spelare/kota-sakurai/15114,Kota Sakurai,https://fotbolltransfers.com/spelare/kota-saku...,15114

In [32]:
resultsTeam

[{'id': 'klubbar/sverige/ifk-goteborg/2',
  'name': 'IFK Göteborg',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/ifk-goteborg/2',
  'numeric_id': 2},
 {'id': 'klubbar/sverige/if-elfsborg/3',
  'name': 'IF Elfsborg',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/if-elfsborg/3',
  'numeric_id': 3},
 {'id': 'klubbar/sverige/aik/4',
  'name': 'AIK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/aik/4',
  'numeric_id': 4},
 {'id': 'klubbar/sverige/assyriska-ff/6',
  'name': 'Assyriska FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/assyriska-ff/6',
  'numeric_id': 6},
 {'id': 'klubbar/sverige/osters-if/7',
  'name': 'Östers IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/osters-if/7',
  'numeric_id': 7},
 {'id': 'spelare/utlandsproffs/norge/8',
  'name': 'Svenska spelare i Norge',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/norge/8',
  'numeric_id': 8},
 {'id': 'klubbar/sverige/hammarby-if/9',
  'name': 'Hammarby IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/hammarby-if/9',
  'numeric_id': 9},
 {'id': 'klubbar/sverige/djurgardens-if/10',
  'name': 'Djurgårdens IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/djurgardens-if/10',
  'numeric_id': 10},
 {'id': 'spelare/utlandsproffs/danmark/11',
  'name': 'Svenska spelare i Danmark',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/danmark/11',
  'numeric_id': 11},
 {'id': 'spelare/utlandsproffs/holland/12',
  'name': 'Svenska spelare i Holland',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/holland/12',
  'numeric_id': 12},
 {'id': 'spelare/utlandsproffs/grekland/13',
  'name': 'Svenska spelare i Grekland',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/grekland/13',
  'numeric_id': 13},
 {'id': 'spelare/utlandsproffs/england/14',
  'name': 'Svenska spelare i England',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/england/14',
  'numeric_id': 14},
 {'id': 'spelare/utlandsproffs/schweiz/15',
  'name': 'Svenska spelare i Schweiz',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/schweiz/15',
  'numeric_id': 15},
 {'id': 'spelare/utlandsproffs/turkiet/16',
  'name': 'Svenska spelare i Turkiet',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/turkiet/16',
  'numeric_id': 16},
 {'id': 'spelare/utlandsproffs/tyskland/17',
  'name': 'Svenska spelare i Tyskland',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/tyskland/17',
  'numeric_id': 17},
 {'id': 'spelare/utlandsproffs/italien/18',
  'name': 'Svenska spelare i Italien',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/italien/18',
  'numeric_id': 18},
 {'id': 'spelare/utlandsproffs/spanien/19',
  'name': 'Svenska spelare i Spanien',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/spanien/19',
  'numeric_id': 19},
 {'id': 'spelare/utlandsproffs/osterrike/20',
  'name': 'Svenska spelare i Österrike',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/osterrike/20',
  'numeric_id': 20},
 {'id': 'spelare/utlandsproffs/ryssland/21',
  'name': 'Svenska spelare i Ryssland',
  'url': 'https://fotbolltransfers.com/spelare/utlandsproffs/ryssland/21',
  'numeric_id': 21},
 {'id': 'klubbar/other/other/22',
  'name': 'other',
  'url': 'https://fotbolltransfers.com/klubbar/other/other/22',
  'numeric_id': 22},
 {'id': 'klubbar/sverige/syrianska-fc/23',
  'name': 'Syrianska FC',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/syrianska-fc/23',
  'numeric_id': 23},
 {'id': 'klubbar/sverige/halmstads-bk/24',
  'name': 'Halmstads BK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/halmstads-bk/24',
  'numeric_id': 24},
 {'id': 'klubbar/sverige/gefle-if/25',
  'name': 'Gefle IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/gefle-if/25',
  'numeric_id': 25},
 {'id': 'klubbar/sverige/if-brommapojkarna/26',
  'name': 'IF Brommapojkarna',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/if-brommapojkarna/26',
  'numeric_id': 26},
 {'id': 'klubbar/sverige/bk-hacken/27',
  'name': 'BK Häcken',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/bk-hacken/27',
  'numeric_id': 27},
 {'id': 'klubbar/sverige/gais/28',
  'name': 'GAIS',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/gais/28',
  'numeric_id': 28},
 {'id': 'klubbar/sverige/helsingborgs-if/29',
  'name': 'Helsingborgs IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/helsingborgs-if/29',
  'numeric_id': 29},
 {'id': 'klubbar/sverige/kalmar-ff/30',
  'name': 'Kalmar FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/kalmar-ff/30',
  'numeric_id': 30},
 {'id': 'klubbar/sverige/malmo-ff/31',
  'name': 'Malmö FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/malmo-ff/31',
  'numeric_id': 31},
 {'id': 'klubbar/sverige/mjallby-aif/32',
  'name': 'Mjällby AIF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/mjallby-aif/32',
  'numeric_id': 32},
 {'id': 'klubbar/sverige/trelleborgs-ff/33',
  'name': 'Trelleborgs FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/trelleborgs-ff/33',
  'numeric_id': 33},
 {'id': 'klubbar/sverige/orebro-sk/34',
  'name': 'Örebro SK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/orebro-sk/34',
  'numeric_id': 34},
 {'id': 'klubbar/sverige/atvidabergs-ff/35',
  'name': 'Åtvidabergs FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/atvidabergs-ff/35',
  'numeric_id': 35},
 {'id': 'klubbar/sverige/degerfors-if/36',
  'name': 'Degerfors IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/degerfors-if/36',
  'numeric_id': 36},
 {'id': 'klubbar/sverige/falkenbergs-ff/37',
  'name': 'Falkenbergs FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/falkenbergs-ff/37',
  'numeric_id': 37},
 {'id': 'klubbar/sverige/fc-trollhattan/38',
  'name': 'FC Trollhättan',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/fc-trollhattan/38',
  'numeric_id': 38},
 {'id': 'klubbar/sverige/gif-sundsvall/39',
  'name': 'GIF Sundsvall',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/gif-sundsvall/39',
  'numeric_id': 39},
 {'id': 'klubbar/sverige/ifk-norrkoping/40',
  'name': 'IFK Norrköping',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/ifk-norrkoping/40',
  'numeric_id': 40},
 {'id': 'klubbar/sverige/ik-brage/41',
  'name': 'IK Brage',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/ik-brage/41',
  'numeric_id': 41},
 {'id': 'klubbar/sverige/jonkopings-sodra-if/42',
  'name': 'Jönköpings Södra IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/jonkopings-sodra-if/42',
  'numeric_id': 42},
 {'id': 'klubbar/sverige/ljungskile-sk/43',
  'name': 'Ljungskile SK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/ljungskile-sk/43',
  'numeric_id': 43},
 {'id': 'klubbar/sverige/vasby-united/44',
  'name': 'Väsby United',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/vasby-united/44',
  'numeric_id': 44},
 {'id': 'klubbar/sverige/angelholms-ff/45',
  'name': 'Ängelholms FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/angelholms-ff/45',
  'numeric_id': 45},
 {'id': 'klubbar/sverige/orgryte-is/46',
  'name': 'Örgryte IS',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/orgryte-is/46',
  'numeric_id': 46},
 {'id': 'klubbar/sverige/landskrona-bois/47',
  'name': 'Landskrona BoIS',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/landskrona-bois/47',
  'numeric_id': 47},
 {'id': 'klubbar/sverige/arameisksyrianska-if/48',
  'name': 'Arameisk-Syrianska IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/arameisksyrianska-if/48',
  'numeric_id': 48},
 {'id': 'klubbar/sverige/bk-forward/49',
  'name': 'BK Forward',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/bk-forward/49',
  'numeric_id': 49},
 {'id': 'klubbar/sverige/bodens-bk-ff/50',
  'name': 'Bodens BK FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/bodens-bk-ff/50',
  'numeric_id': 50},
 {'id': 'klubbar/sverige/carlstad-united/51',
  'name': 'Carlstad United',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/carlstad-united/51',
  'numeric_id': 51},
 {'id': 'klubbar/sverige/dalkurd-ff/52',
  'name': 'Dalkurd FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/dalkurd-ff/52',
  'numeric_id': 52},
 {'id': 'klubbar/sverige/grondals-ik/53',
  'name': 'Gröndals IK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/grondals-ik/53',
  'numeric_id': 53},
 {'id': 'klubbar/sverige/hammarby-tff/54',
  'name': 'Hammarby TFF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/hammarby-tff/54',
  'numeric_id': 54},
 {'id': 'klubbar/sverige/ik-sirius/55',
  'name': 'IK Sirius',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/ik-sirius/55',
  'numeric_id': 55},
 {'id': 'klubbar/sverige/syrianska-if-kerburan/56',
  'name': 'Syrianska IF Kerburan',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/syrianska-if-kerburan/56',
  'numeric_id': 56},
 {'id': 'klubbar/sverige/umea-fc/57',
  'name': 'Umeå FC',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/umea-fc/57',
  'numeric_id': 57},
 {'id': 'klubbar/sverige/valsta-syrianska-ik/58',
  'name': 'Valsta Syrianska IK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/valsta-syrianska-ik/58',
  'numeric_id': 58},
 {'id': 'klubbar/sverige/vasalund-if/59',
  'name': 'Vasalund IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/vasalund-if/59',
  'numeric_id': 59},
 {'id': 'klubbar/sverige/vasteras-sk/60',
  'name': 'Västerås SK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/vasteras-sk/60',
  'numeric_id': 60},
 {'id': 'klubbar/sverige/ostersunds-fk/61',
  'name': 'Östersunds FK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/ostersunds-fk/61',
  'numeric_id': 61},
 {'id': 'klubbar/sverige/lb07/62',
  'name': 'LB07',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/lb07/62',
  'numeric_id': 62},
 {'id': 'klubbar/sverige/fc-rosengard/63',
  'name': 'FC Rosengård',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/fc-rosengard/63',
  'numeric_id': 63},
 {'id': 'klubbar/sverige/husqvarna-ff/64',
  'name': 'Husqvarna FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/husqvarna-ff/64',
  'numeric_id': 64},
 {'id': 'klubbar/sverige/if-sylvia/65',
  'name': 'IF Sylvia',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/if-sylvia/65',
  'numeric_id': 65},
 {'id': 'klubbar/sverige/ifk-varnamo/66',
  'name': 'IFK Värnamo',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/ifk-varnamo/66',
  'numeric_id': 66},
 {'id': 'klubbar/sverige/ik-sleipner/67',
  'name': 'IK Sleipner',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/ik-sleipner/67',
  'numeric_id': 67},
 {'id': 'klubbar/sverige/kristianstads-ff/68',
  'name': 'Kristianstads FF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/kristianstads-ff/68',
  'numeric_id': 68},
 {'id': 'klubbar/sverige/lunds-bk/69',
  'name': 'Lunds BK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/lunds-bk/69',
  'numeric_id': 69},
 {'id': 'klubbar/sverige/norrby-if/70',
  'name': 'Norrby IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/norrby-if/70',
  'numeric_id': 70},
 {'id': 'klubbar/sverige/qviding-fif/71',
  'name': 'Qviding FIF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/qviding-fif/71',
  'numeric_id': 71},
 {'id': 'klubbar/sverige/skovde-aik/72',
  'name': 'Skövde AIK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/skovde-aik/72',
  'numeric_id': 72},
 {'id': 'klubbar/sverige/torslanda-ik/73',
  'name': 'Torslanda IK',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/torslanda-ik/73',
  'numeric_id': 73},
 {'id': 'klubbar/sverige/vastra-frolunda-if/74',
  'name': 'Västra Frölunda IF',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/vastra-frolunda-if/74',
  'numeric_id': 74},
 {'id': 'klubbar/sverige/ytterby-is/75',
  'name': 'Ytterby IS',
  'url': 'https://fotbolltransfers.com/klubbar/sverige/ytterby-is/75',
  'numeric_id': 75},
 {'id': 'klubbar/italien/fc-inter/76',
  'name': 'FC Inter',
  'url': 'https://fotbolltransfers.com/klubbar/italien/fc-inter/76',
  'numeric_id': 76},
 {'id': 'klubbar/italien/ac-milan/77',
  'name': 'AC Milan',
  'url': 'https://fotbolltransfers.com/klubbar/italien/ac-milan/77',
  'numeric_id': 77},
 {'id': 'klubbar/italien/juventus-fc/78',
  'name': 'Juventus FC',
  'url': 'https://fotbolltransfers.com/klubbar/italien/juventus-fc/78',
  'numeric_id': 78},
 {'id': 'klubbar/italien/as-roma/79',
  'name': 'AS Roma',
  'url': 'https://fotbolltransfers.com/klubbar/italien/as-roma/79',
  'numeric_id': 79},
 {'id': 'klubbar/italien/acf-fiorentina/80',
  'name': 'ACF Fiorentina',
  'url': 'https://fotbolltransfers.com/klubbar/italien/acf-fiorentina/80',
  'numeric_id': 80},
 {'id': 'klubbar/england/manchester-united/81',
  'name': 'Manchester United',
  'url': 'https://fotbolltransfers.com/klubbar/england/manchester-united/81',
  'numeric_id': 81},
 {'id': 'klubbar/england/liverpool-fc/82',
  'name': 'Liverpool FC',
  'url': 'https://fotbolltransfers.com/klubbar/england/liverpool-fc/82',
  'numeric_id': 82},
 {'id': 'klubbar/england/arsenal-fc/83',
  'name': 'Arsenal FC',
  'url': 'https://fotbolltransfers.com/klubbar/england/arsenal-fc/83',
  'numeric_id': 83},
 {'id': 'klubbar/england/chelsea-fc/84',
  'name': 'Chelsea FC',
  'url': 'https://fotbolltransfers.com/klubbar/england/chelsea-fc/84',
  'numeric_id': 84},
 {'id': 'klubbar/spanien/fc-barcelona/85',
  'name': 'FC Barcelona',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/fc-barcelona/85',
  'numeric_id': 85},
 {'id': 'klubbar/spanien/real-madrid/86',
  'name': 'Real Madrid',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/real-madrid/86',
  'numeric_id': 86},
 {'id': 'klubbar/spanien/valencia-cf/87',
  'name': 'Valencia CF',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/valencia-cf/87',
  'numeric_id': 87},
 {'id': 'klubbar/spanien/sevilla-fc/88',
  'name': 'Sevilla FC',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/sevilla-fc/88',
  'numeric_id': 88},
 {'id': 'klubbar/holland/afc-ajax/89',
  'name': 'AFC Ajax',
  'url': 'https://fotbolltransfers.com/klubbar/holland/afc-ajax/89',
  'numeric_id': 89},
 {'id': 'klubbar/tyskland/bayer-leverkusen/90',
  'name': 'Bayer Leverkusen',
  'url': 'https://fotbolltransfers.com/klubbar/tyskland/bayer-leverkusen/90',
  'numeric_id': 90},
 {'id': 'klubbar/tyskland/bayern-munchen/91',
  'name': 'Bayern München',
  'url': 'https://fotbolltransfers.com/klubbar/tyskland/bayern-munchen/91',
  'numeric_id': 91},
 {'id': 'klubbar/tyskland/fc-schalke-04/92',
  'name': 'FC Schalke 04',
  'url': 'https://fotbolltransfers.com/klubbar/tyskland/fc-schalke-04/92',
  'numeric_id': 92},
 {'id': 'klubbar/tyskland/hamburger-sv/93',
  'name': 'Hamburger SV',
  'url': 'https://fotbolltransfers.com/klubbar/tyskland/hamburger-sv/93',
  'numeric_id': 93},
 {'id': 'klubbar/tyskland/borussia-dortmund/94',
  'name': 'Borussia Dortmund',
  'url': 'https://fotbolltransfers.com/klubbar/tyskland/borussia-dortmund/94',
  'numeric_id': 94},
 {'id': 'klubbar/tyskland/werder-bremen/95',
  'name': 'Werder Bremen',
  'url': 'https://fotbolltransfers.com/klubbar/tyskland/werder-bremen/95',
  'numeric_id': 95},
 {'id': 'klubbar/tyskland/vfl-wolfsburg/96',
  'name': 'VfL Wolfsburg',
  'url': 'https://fotbolltransfers.com/klubbar/tyskland/vfl-wolfsburg/96',
  'numeric_id': 96},
 {'id': 'klubbar/italien/parma-calcio-1913/97',
  'name': 'Parma Calcio 1913',
  'url': 'https://fotbolltransfers.com/klubbar/italien/parma-calcio-1913/97',
  'numeric_id': 97},
 {'id': 'klubbar/tyskland/vfb-stuttgart/98',
  'name': 'VfB Stuttgart',
  'url': 'https://fotbolltransfers.com/klubbar/tyskland/vfb-stuttgart/98',
  'numeric_id': 98},
 {'id': 'klubbar/italien/ssc-napoli/99',
  'name': 'SSC Napoli',
  'url': 'https://fotbolltransfers.com/klubbar/italien/ssc-napoli/99',
  'numeric_id': 99},
 {'id': 'klubbar/italien/palermo-fc/100',
  'name': 'Palermo FC',
  'url': 'https://fotbolltransfers.com/klubbar/italien/palermo-fc/100',
  'numeric_id': 100},
 {'id': 'klubbar/italien/uc-sampdoria/101',
  'name': 'UC Sampdoria',
  'url': 'https://fotbolltransfers.com/klubbar/italien/uc-sampdoria/101',
  'numeric_id': 101},
 {'id': 'klubbar/ovriga-europa/as-bari/102',
  'name': 'AS Bari',
  'url': 'https://fotbolltransfers.com/klubbar/ovriga-europa/as-bari/102',
  'numeric_id': 102},
 {'id': 'klubbar/italien/genoa-cfc/103',
  'name': 'Genoa CFC',
  'url': 'https://fotbolltransfers.com/klubbar/italien/genoa-cfc/103',
  'numeric_id': 103},
 {'id': 'klubbar/ovriga-europa/ac-chievo/104',
  'name': 'AC Chievo',
  'url': 'https://fotbolltransfers.com/klubbar/ovriga-europa/ac-chievo/104',
  'numeric_id': 104},
 {'id': 'klubbar/italien/cagliari-calcio/105',
  'name': 'Cagliari Calcio',
  'url': 'https://fotbolltransfers.com/klubbar/italien/cagliari-calcio/105',
  'numeric_id': 105},
 {'id': 'klubbar/italien/udinese-calcio/106',
  'name': 'Udinese Calcio',
  'url': 'https://fotbolltransfers.com/klubbar/italien/udinese-calcio/106',
  'numeric_id': 106},
 {'id': 'klubbar/italien/bologna-fc/107',
  'name': 'Bologna FC',
  'url': 'https://fotbolltransfers.com/klubbar/italien/bologna-fc/107',
  'numeric_id': 107},
 {'id': 'klubbar/ovriga-europa/as-livorno/108',
  'name': 'AS Livorno',
  'url': 'https://fotbolltransfers.com/klubbar/ovriga-europa/as-livorno/108',
  'numeric_id': 108},
 {'id': 'klubbar/italien/ss-lazio/109',
  'name': 'SS Lazio',
  'url': 'https://fotbolltransfers.com/klubbar/italien/ss-lazio/109',
  'numeric_id': 109},
 {'id': 'klubbar/italien/atalanta-bc/110',
  'name': 'Atalanta BC',
  'url': 'https://fotbolltransfers.com/klubbar/italien/atalanta-bc/110',
  'numeric_id': 110},
 {'id': 'klubbar/ovriga-europa/catania-fc/111',
  'name': 'Catania FC',
  'url': 'https://fotbolltransfers.com/klubbar/ovriga-europa/catania-fc/111',
  'numeric_id': 111},
 {'id': 'klubbar/ovriga-europa/ac-siena/112',
  'name': 'AC Siena',
  'url': 'https://fotbolltransfers.com/klubbar/ovriga-europa/ac-siena/112',
  'numeric_id': 112},
 {'id': 'klubbar/spanien/rcd-mallorca/113',
  'name': 'RCD Mallorca',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/rcd-mallorca/113',
  'numeric_id': 113},
 {'id': 'klubbar/spanien/deportivo-la-coruna/114',
  'name': 'Deportivo La Coruna',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/deportivo-la-coruna/114',
  'numeric_id': 114},
 {'id': 'klubbar/spanien/athletic-bilbao/115',
  'name': 'Athletic Bilbao',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/athletic-bilbao/115',
  'numeric_id': 115},
 {'id': 'klubbar/spanien/getafe-cf/116',
  'name': 'Getafe CF',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/getafe-cf/116',
  'numeric_id': 116},
 {'id': 'klubbar/spanien/villarreal-cf/117',
  'name': 'Villarreal CF',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/villarreal-cf/117',
  'numeric_id': 117},
 {'id': 'klubbar/spanien/sporting-gijon/118',
  'name': 'Sporting Gijón',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/sporting-gijon/118',
  'numeric_id': 118},
 {'id': 'klubbar/spanien/real-valladolid/119',
  'name': 'Real Valladolid',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/real-valladolid/119',
  'numeric_id': 119},
 {'id': 'klubbar/spanien/ca-osasuna/120',
  'name': 'CA Osasuna',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/ca-osasuna/120',
  'numeric_id': 120},
 {'id': 'klubbar/spanien/rcd-espanyol/121',
  'name': 'RCD Espanyol',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/rcd-espanyol/121',
  'numeric_id': 121},
 {'id': 'klubbar/ovriga-europa/cd-tenerife/122',
  'name': 'CD Tenerife',
  'url': 'https://fotbolltransfers.com/klubbar/ovriga-europa/cd-tenerife/122',
  'numeric_id': 122},
 {'id': 'klubbar/spanien/atletico-madrid/123',
  'name': 'Atlético Madrid',
  'url': 'https://fotbolltransfers.com/klubbar/spanien/atletico-madrid/123',
  'numeric_id': 123},

In [33]:
dfTeam = pd.DataFrame(resultsTeam,columns=['id','name','url','numeric_id'])

In [34]:
dfTeam

,id,name,url,numeric_id
0,klubbar/sverige/ifk-goteborg/2,IFK Göteborg,https://fotbolltransfers.com/klubbar/sverige/i...,2
1,klubbar/sverige/if-elfsborg/3,IF Elfsborg,https://fotbolltransfers.com/klubbar/sverige/i...,3
2,klubbar/sverige/aik/4,AIK,https://fotbolltransfers.com/klubbar/sverige/a...,4
3,klubbar/sverige/assyriska-ff/6,Assyriska FF,https://fotbolltransfers.com/klubbar/sverige/a...,6
4,klubbar/sverige/osters-if/7,Östers IF,https://fotbolltransfers.com/klubbar/sverige/o...,7
...,...,...,...,...
6687,klubbar/ovriga-europa/mexico-fc/6795,México FC,https://fotbolltransfers.com/klubbar/ovriga-eu...,6795
6688,klubbar/sverige/fk-karlskrona-u16/6796,FK Karlskrona U16,https://fotbolltransfers.com/klubbar/sverige/f...,6796
6689,klubbar/ovriga-europa/rodina-moskva/6797,Rodina Moskva,https://fotbolltransfers.com/klubbar/ovriga-eu...,6797
6690,klubbar/ovriga-europa/fc-inter-u23/6798,FC Inter U23,https://fotbolltransfers.com/klubbar/ovriga-eu...,6798
6691,klubbar/varlden/toluca-fc-d/6799,Toluca FC (D),https://fotbolltransfers.com/klubbar/varlden/t...,6799

### MixandMatch  
id,name,desc,type,url

In [35]:
dfTeam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6692 entries, 0 to 6691
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          6692 non-null   object
 1   name        6692 non-null   object
 2   url         6692 non-null   object
 3   numeric_id  6692 non-null   int64
dtypes: int64(1), object(3)
memory usage: 209.3+ KB

In [36]:
import pandas as pd
from datetime import datetime

# ===== KONFIG =====
TYPE_PLAYER = "Q5"        # människa
TYPE_TEAM = "Q476028"     # fotbollsklubb

# ===== FILNAMN =====
today = datetime.now().strftime("%Y%m%d")
filename = f"41_fotbolltransfers_mixnmatch_{today}.csv"

# ===== BYGG DATA =====

# Spelare
df_players_out = dfPlayers.copy()
df_players_out["desc"] = "fotbollsspelare"
df_players_out["type"] = TYPE_PLAYER

# Klubb
df_team_out = dfTeam.copy()
df_team_out["desc"] = "fotbollsklubb"
df_team_out["type"] = TYPE_TEAM

# ===== KOMBINERA =====
df_out = pd.concat([df_players_out, df_team_out], ignore_index=True)

# ===== VÄLJ KOLUMNER =====
df_out = df_out[["id", "name", "desc", "type", "url"]]

# ===== EXPORT =====
df_out.to_csv(filename, index=False, encoding="utf-8")

print(f"Fil skapad: {filename}")

Fil skapad: 41_fotbolltransfers_mixnmatch_20260323.csv

In [14]:
 # End timer and calculate duration
end_time = time.time()
elapsed_time = end_time - start_time# Bygg audit-lager för den här etappen

# Print current date and total time
print("Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
minutes, seconds = divmod(elapsed_time, 60)
print("Total time elapsed: {:02.0f} minutes {:05.2f} seconds".format(minutes, seconds))

Date: 2026-03-20 21:03:15
Total time elapsed: 413 minutes 17.43 seconds